function metrics = compute_respiratory_phase_offset_metrics(data, resp_cycles, config)
% COMPUTE_RESPIRATORY_PHASE_OFFSET_METRICS Measure thoracoabdominal phase offset.
% This complementary MAGMA method uses aligned wavelet coefficients from both
% recorded-polarity belts at one shared respiratory frequency. It is motivated
% by phase-angle approaches in Motto et al. (2005) and Chen and Hsiao (2016),
% but is not an exact reproduction of either publication. No belt inversion,
% time shifting, absolute-value transform, or session-reference normalization
% is applied. Invalid gaps are not interpolated or bridged by summary windows.

    N = size(data, 1);
    t_grid = (0:config.grid_step_sec:(N - 1) / config.fs)';
    metrics = empty_phase_offset_metrics(t_grid, config);
    metrics.master_n_samples = N;

    if ~isfield(config, 'channels')
        config = resolve_signal_channels(config);
    end
    idx_lungs = config.channels.lungs_idx;
    idx_diaph = config.channels.diaph_idx;
    if isempty(idx_lungs) || isempty(idx_diaph)
        metrics.availability_reason = 'missing_respiratory_belt_channel';
        return;
    end
    if is_lung_belt_ignored(config)
        metrics.availability_reason = 'lung_belt_marked_missing';
        return;
    end
    if ~isempty(resp_cycles) && ...
            ~is_valid_breath_signal(resp_cycles.lungs, false)
        metrics.availability_reason = 'invalid_lungs_breath_timing';
        return;
    end
    if ~isempty(resp_cycles) && ...
            ~is_valid_breath_signal(resp_cycles.diaph, false)
        metrics.availability_reason = 'invalid_diaphragm_breath_timing';
        return;
    end

    [lungs, lungs_finite, lungs_ok] = ...
        prepare_phase_signal(data(:, idx_lungs));
    [diaph, diaph_finite, diaph_ok] = ...
        prepare_phase_signal(data(:, idx_diaph));
    if ~lungs_ok || ~diaph_ok
        metrics.availability_reason = 'flat_or_invalid_respiratory_signal';
        return;
    end

    old_visibility = get(groot, 'defaultFigureVisible');
    existing_figures = findall(groot, 'Type', 'figure');
    target_visibility = phase_figure_visibility(config);
    cleanup = onCleanup(@() restore_phase_figure_visibility( ...
        old_visibility, existing_figures, target_visibility));
    set(groot, 'defaultFigureVisible', target_visibility);

    try
        [lungs_analysis, diaph_analysis, fs_analysis] = ...
            resample_respiration_for_analysis( ...
                lungs, diaph, config.fs, metrics.analysis_fs);
        metrics.analysis_fs = fs_analysis;
        metrics.analysis_n_samples = numel(lungs_analysis);
        metrics.analysis_duration_sec = ...
            max(0, metrics.analysis_n_samples - 1) / fs_analysis;
        analysis_t = (0:metrics.analysis_n_samples - 1)' / fs_analysis;
        master_idx = min(N, max(1, round(analysis_t * config.fs) + 1));
        input_valid = lungs_finite(master_idx) & diaph_finite(master_idx);

        fmax = min(metrics.frequency_max_hz, 0.95 * fs_analysis / 2);
        if metrics.frequency_min_hz >= fmax
            metrics.availability_reason = 'invalid_respiratory_frequency_range';
            return;
        end
        [wt_lungs, frequency] = wtI(lungs_analysis, fs_analysis, ...
            'fmin', metrics.frequency_min_hz, 'fmax', fmax, ...
            'f0', metrics.f0, 'Plot', 'off', 'Display', 'off', ...
            'CutEdges', 'on', 'Padding', 'none');
        [wt_diaph, frequency_diaph] = wtI(diaph_analysis, fs_analysis, ...
            'fmin', metrics.frequency_min_hz, 'fmax', fmax, ...
            'f0', metrics.f0, 'Plot', 'off', 'Display', 'off', ...
            'CutEdges', 'on', 'Padding', 'none');
        [wt_lungs, wt_diaph, frequency] = align_phase_wavelets( ...
            wt_lungs, wt_diaph, frequency, frequency_diaph);
        if isempty(frequency) || isempty(wt_lungs) || isempty(wt_diaph)
            metrics.availability_reason = 'empty_wavelet_output';
            return;
        end
    catch ME
        metrics.availability_reason = 'wavelet_computation_failed';
        metrics.error_message = ME.message;
        warning('MAGMA:RespiratoryPhaseOffset:Skipped', ...
            'Respiratory phase-offset metrics skipped: %s', ME.message);
        return;
    end

    [phase_rad, selected_frequency, coefficient_valid, magnitude_floors] = ...
        shared_frequency_phase(wt_lungs, wt_diaph, frequency, ...
            input_valid, metrics.min_magnitude_fraction);
    metrics.magnitude_floors = magnitude_floors;
    [metrics.signed_mean_phase_deg, metrics.resultant_length, ...
        metrics.selected_resp_frequency_hz, metrics.valid_phase_mask] = ...
        summarize_phase_on_grid(phase_rad, selected_frequency, ...
            coefficient_valid, input_valid, fs_analysis, t_grid, ...
            metrics.summary_cycles, metrics.min_valid_fraction);
    metrics.absolute_mean_phase_deg = abs(metrics.signed_mean_phase_deg);
    metrics.reliable_phase_mask = metrics.valid_phase_mask & ...
        metrics.resultant_length >= metrics.min_resultant_length;
    metrics.candidate_mask = metrics.reliable_phase_mask & ...
        metrics.absolute_mean_phase_deg >= metrics.angle_threshold_deg;
    metrics.available = any(metrics.reliable_phase_mask);
    if metrics.available
        metrics.availability_reason = 'available';
    elseif any(metrics.valid_phase_mask)
        metrics.availability_reason = 'no_reliable_circular_phase_summary';
    else
        metrics.availability_reason = 'no_valid_shared_frequency_phase_evidence';
    end
end

function metrics = empty_phase_offset_metrics(t_grid, config)
% EMPTY_PHASE_OFFSET_METRICS Initialize compact phase-offset evidence.

    metrics = struct( ...
        'method', 'wavelet_phase_offset', ...
        'available', false, ...
        'availability_reason', 'not_evaluated', ...
        'error_message', '', ...
        'time_sec', t_grid, ...
        'signed_mean_phase_deg', nan(size(t_grid)), ...
        'absolute_mean_phase_deg', nan(size(t_grid)), ...
        'resultant_length', nan(size(t_grid)), ...
        'selected_resp_frequency_hz', nan(size(t_grid)), ...
        'valid_phase_mask', false(size(t_grid)), ...
        'reliable_phase_mask', false(size(t_grid)), ...
        'candidate_mask', false(size(t_grid)), ...
        'event_mask', false(size(t_grid)), ...
        'events', empty_events(), ...
        'analysis_fs', get_config_value(config, 'async', 'analysis_fs', ...
            min(config.fs, 20)), ...
        'analysis_n_samples', 0, ...
        'analysis_duration_sec', 0, ...
        'master_fs', config.fs, ...
        'master_n_samples', 0, ...
        'f0', get_config_value(config, 'async', 'f0', 1), ...
        'frequency_min_hz', phase_setting(config, 'frequency_min_hz', ...
            get_config_value(config, 'async', 'low_mid_cut_hz', 0.145)), ...
        'frequency_max_hz', phase_setting(config, 'frequency_max_hz', ...
            get_config_value(config, 'async', 'mid_high_cut_hz', 0.6)), ...
        'angle_threshold_deg', phase_setting(config, ...
            'angle_threshold_deg', 30), ...
        'summary_cycles', phase_setting(config, 'summary_cycles', 5), ...
        'min_resultant_length', phase_setting(config, ...
            'min_resultant_length', 0.80), ...
        'min_valid_fraction', phase_setting(config, ...
            'min_valid_fraction', 0.80), ...
        'min_magnitude_fraction', phase_setting(config, ...
            'min_magnitude_fraction', 0.05), ...
        'magnitude_floors', struct('lungs', NaN, 'diaph', NaN), ...
        'min_dur_sec', get_config_value(config, 'async', 'min_dur_sec', 30), ...
        'polarity_convention', ...
            'recorded_channel_polarity_thoracic_minus_abdominal_no_inversion', ...
        'frequency_selection', ...
            'maximum_joint_wavelet_magnitude_at_one_shared_respiratory_frequency', ...
        'reference_normalization', 'none', ...
        'literature_motivation', ...
            'Motto_2005_10.1109/TBME.2005.844026;Chen_Hsiao_2016_10.1186/s12938-016-0233-7', ...
        'implementation_scope', ...
            'MAGMA_wavelet_phase_offset_not_exact_tidal_volume_replication', ...
        'provenance', struct( ...
            'polarity_convention', ...
                'recorded_channel_polarity_thoracic_minus_abdominal_no_inversion', ...
            'frequency_selection', ...
                'maximum_joint_wavelet_magnitude_at_one_shared_respiratory_frequency', ...
            'reference_normalization', 'none', ...
            'literature_motivation', ...
                ['Motto_2005_10.1109/TBME.2005.844026;' ...
                 'Chen_Hsiao_2016_10.1186/s12938-016-0233-7'], ...
            'implementation_scope', ...
                'MAGMA_wavelet_phase_offset_not_exact_tidal_volume_replication'));
    validate_phase_settings(metrics);
end

function value = phase_setting(config, name, default_value)
% PHASE_SETTING Read one nested config.async.phase_offset value.

    value = default_value;
    if isfield(config, 'async') && isfield(config.async, 'phase_offset') && ...
            isfield(config.async.phase_offset, name)
        value = config.async.phase_offset.(name);
    end
end

function validate_phase_settings(metrics)
% VALIDATE_PHASE_SETTINGS Reject invalid operational comparison settings.

    positive = {'analysis_fs', 'frequency_min_hz', 'frequency_max_hz', ...
        'summary_cycles', 'min_dur_sec'};
    for i = 1:numel(positive)
        value = metrics.(positive{i});
        if ~isscalar(value) || ~isfinite(value) || value <= 0
            error('MAGMA:RespiratoryPhaseOffset:InvalidSetting', ...
                '%s must be a finite positive scalar.', positive{i});
        end
    end
    if metrics.frequency_min_hz >= metrics.frequency_max_hz || ...
            ~isscalar(metrics.angle_threshold_deg) || ...
            ~isfinite(metrics.angle_threshold_deg) || ...
            metrics.angle_threshold_deg < 0 || metrics.angle_threshold_deg > 180 || ...
            ~isscalar(metrics.min_resultant_length) || ...
            ~isfinite(metrics.min_resultant_length) || ...
            metrics.min_resultant_length < 0 || metrics.min_resultant_length > 1 || ...
            ~isscalar(metrics.min_valid_fraction) || ...
            ~isfinite(metrics.min_valid_fraction) || ...
            metrics.min_valid_fraction <= 0 || metrics.min_valid_fraction > 1 || ...
            ~isscalar(metrics.min_magnitude_fraction) || ...
            ~isfinite(metrics.min_magnitude_fraction) || ...
            metrics.min_magnitude_fraction < 0
        error('MAGMA:RespiratoryPhaseOffset:InvalidSetting', ...
            'Invalid phase-offset frequency, angle, reliability, or validity setting.');
    end
end

function [x, finite_mask, ok] = prepare_phase_signal(x)
% PREPARE_PHASE_SIGNAL Center/scale finite data without gap interpolation.

    x = x(:);
    finite_mask = isfinite(x);
    ok = nnz(finite_mask) >= 2;
    if ~ok
        return;
    end
    center = median(x(finite_mask), 'omitnan');
    x(finite_mask) = x(finite_mask) - center;
    scale = 1.4826 * median(abs(x(finite_mask)), 'omitnan');
    if ~isfinite(scale) || scale <= eps
        scale = std(x(finite_mask), 'omitnan');
    end
    ok = isfinite(scale) && scale > eps;
    if ~ok
        return;
    end
    x(finite_mask) = x(finite_mask) ./ scale;
    x(~finite_mask) = 0;
end

function [wt1, wt2, frequency] = align_phase_wavelets( ...
    wt1, wt2, frequency1, frequency2)
% ALIGN_PHASE_WAVELETS Crop transforms to common frequency/time dimensions.

    nf = min([size(wt1, 1), size(wt2, 1), ...
        numel(frequency1), numel(frequency2)]);
    nt = min(size(wt1, 2), size(wt2, 2));
    if nf < 1 || nt < 1
        wt1 = [];
        wt2 = [];
        frequency = [];
        return;
    end
    wt1 = wt1(1:nf, 1:nt);
    wt2 = wt2(1:nf, 1:nt);
    frequency = frequency1(1:nf);
end

function [phase_rad, selected_frequency, valid, floors] = ...
    shared_frequency_phase(wt_lungs, wt_diaph, frequency, input_valid, fraction)
% SHARED_FREQUENCY_PHASE Select one joint-magnitude frequency per time point.

    nt = min([size(wt_lungs, 2), size(wt_diaph, 2), numel(input_valid)]);
    wt_lungs = wt_lungs(:, 1:nt);
    wt_diaph = wt_diaph(:, 1:nt);
    input_valid = logical(input_valid(1:nt));
    joint_magnitude = sqrt(abs(wt_lungs) .* abs(wt_diaph));
    [~, row] = max(joint_magnitude, [], 1);
    column = 1:nt;
    linear = sub2ind(size(wt_lungs), row, column);
    selected_lungs = wt_lungs(linear).';
    selected_diaph = wt_diaph(linear).';
    selected_frequency = frequency(row(:));
    phase_rad = angle(selected_lungs .* conj(selected_diaph));

    lung_scale = median(max(abs(wt_lungs), [], 1), 'omitnan');
    diaph_scale = median(max(abs(wt_diaph), [], 1), 'omitnan');
    floors = struct( ...
        'lungs', max(eps, fraction * lung_scale), ...
        'diaph', max(eps, fraction * diaph_scale));
    valid = input_valid & isfinite(phase_rad) & ...
        isfinite(selected_frequency) & selected_frequency > 0 & ...
        abs(selected_lungs) >= floors.lungs & ...
        abs(selected_diaph) >= floors.diaph;
    phase_rad(~valid) = NaN;
    selected_frequency(~valid) = NaN;
end

function [mean_deg, resultant, frequency_grid, valid_grid] = ...
    summarize_phase_on_grid(phase_rad, selected_frequency, coefficient_valid, ...
        input_valid, fs, t_grid, summary_cycles, min_valid_fraction)
% SUMMARIZE_PHASE_ON_GRID Compute centered circular means within valid blocks.

    mean_deg = nan(size(t_grid));
    resultant = nan(size(t_grid));
    frequency_grid = nan(size(t_grid));
    valid_grid = false(size(t_grid));
    n = numel(phase_rad);
    for g = 1:numel(t_grid)
        center = round(t_grid(g) * fs) + 1;
        if center < 1 || center > n || ~coefficient_valid(center)
            continue;
        end
        f_center = selected_frequency(center);
        half_window = ceil(0.5 * summary_cycles * fs / f_center);
        first = center - half_window;
        last = center + half_window;
        if first < 1 || last > n || ~all(input_valid(first:last))
            continue;
        end
        window_valid = coefficient_valid(first:last);
        if nnz(window_valid) / numel(window_valid) < min_valid_fraction
            continue;
        end
        values = phase_rad(first:last);
        values = values(window_valid);
        [mean_phase, r] = circular_phase_summary(values);
        if ~isfinite(mean_phase) || ~isfinite(r)
            continue;
        end
        mean_deg(g) = rad2deg(mean_phase);
        resultant(g) = r;
        frequency_grid(g) = median( ...
            selected_frequency(first - 1 + find(window_valid)), 'omitnan');
        valid_grid(g) = isfinite(frequency_grid(g));
    end
end

function visibility = phase_figure_visibility(config)
% PHASE_FIGURE_VISIBILITY Resolve wavelet-library figure visibility.

    visibility = 'on';
    if isfield(config, 'make_figs_visible') && ~isempty(config.make_figs_visible)
        visibility = char(string(config.make_figs_visible));
    end
end

function restore_phase_figure_visibility(old, existing, target)
% RESTORE_PHASE_FIGURE_VISIBILITY Restore root state and close hidden figures.

    set(groot, 'defaultFigureVisible', old);
    if strcmpi(target, 'off')
        current = findall(groot, 'Type', 'figure');
        created = setdiff(current, existing);
        if ~isempty(created)
            close(created(ishandle(created)));
        end
    end
end
