function diagnostics = compute_guyot_periodic_breathing( ...
    data, resp_cycles, config)
% COMPUTE_GUYOT_PERIODIC_BREATHING Estimate periodic modulation with Matrix Pencil.
% This is a MAGMA adaptation of Guyot et al. 2020: modulation estimation and
% published h/fm decisions are retained, while the paper's breath front-end is
% replaced by reviewed MAGMA peak_t and canonical amp values.

    cfg = validate_guyot_config(config.periodic.guyot);
    N = size(data, 1);
    recording_end_t = max(0, (N - 1) / config.fs);
    lungs_ignored = is_lung_belt_ignored(config);

    lungs = empty_guyot_belt(recording_end_t, cfg);
    if ~lungs_ignored && isfield(resp_cycles, 'lungs')
        lungs = compute_guyot_belt( ...
            resp_cycles.lungs, recording_end_t, N, config.fs, cfg);
    end
    diaph = empty_guyot_belt(recording_end_t, cfg);
    if isfield(resp_cycles, 'diaph')
        diaph = compute_guyot_belt( ...
            resp_cycles.diaph, recording_end_t, N, config.fs, cfg);
    end

    combined_generic = combine_periodic_belt_evidence( ...
        lungs.envelope_t, lungs.evaluable_time_mask, ...
        lungs.pathological_time_mask, diaph.evaluable_time_mask, ...
        diaph.pathological_time_mask, cfg.min_zone_sec, N, config.fs);
    combined = struct( ...
        'available', combined_generic.available, ...
        't_sec', combined_generic.t_sec, ...
        'evaluable_mask', combined_generic.evaluable_mask, ...
        'pathological_mask', combined_generic.positive_mask, ...
        'candidate_mask', combined_generic.candidate_mask, ...
        'candidate_events', combined_generic.candidate_events, ...
        'events', combined_generic.events);

    diagnostics = struct( ...
        'available', combined.available, ...
        'method_name', 'Demodulation / Matrix Pencil', ...
        'method', 'MAGMA adaptation of Guyot et al. 2020', ...
        'reference_doi', '10.1371/journal.pone.0221191', ...
        'implementation', 'MAGMA adaptation using reviewed MAGMA breaths', ...
        'front_end_note', ['Periodic-modulation estimation follows Guyot; ' ...
            'published change-point breath extraction is replaced by reviewed ' ...
            'MAGMA peak times and canonical breath amplitudes.'], ...
        'belt_combination', ['MAGMA dynamic rule: require both belts when both ' ...
            'are evaluable; otherwise use the single evaluable belt.'], ...
        'resample_hz', cfg.resample_hz, ...
        'window_sec', cfg.window_sec, ...
        'overlap_fraction', cfg.overlap_fraction, ...
        'step_sec', cfg.step_sec, ...
        'h_threshold', cfg.h_threshold, ...
        'fm_band_hz', cfg.fm_band_hz, ...
        'min_zone_sec', cfg.min_zone_sec, ...
        'gap_factor', cfg.gap_factor, ...
        'matrix_pencil_model_order', 3, ...
        'lungs', lungs, ...
        'diaph', diaph, ...
        'combined', combined);
end

function diagnostics = compute_guyot_belt( ...
    breaths, recording_end_t, N, fs, cfg)
% COMPUTE_GUYOT_BELT Reconstruct one belt and estimate sliding-window h/fm.

    diagnostics = empty_guyot_belt(recording_end_t, cfg);
    if isempty(breaths) || ~isstruct(breaths) || ...
            (isfield(breaths, 'ok') && ~breaths.ok) || ...
            ~isfield(breaths, 'peak_t') || ~isfield(breaths, 'amp')
        return;
    end
    reconstruction = reconstruct_guyot_envelope( ...
        breaths.peak_t, breaths.amp, recording_end_t, ...
        cfg.resample_hz, cfg.gap_factor);
    diagnostics.breath_t = reconstruction.breath_t;
    diagnostics.canonical_breath_amp = reconstruction.canonical_breath_amp;
    diagnostics.median_ibi_sec = reconstruction.median_ibi_sec;
    diagnostics.envelope_t = reconstruction.envelope_t;
    diagnostics.envelope = reconstruction.envelope;
    diagnostics.envelope_evaluable_mask = reconstruction.evaluable_mask;
    diagnostics.long_gap_mask = reconstruction.long_gap_mask;

    n_window_samples = round(cfg.window_sec * cfg.resample_hz) + 1;
    step_samples = max(1, round(cfg.step_sec * cfg.resample_hz));
    last_start = numel(diagnostics.envelope) - n_window_samples + 1;
    if ~reconstruction.available || last_start < 1
        return;
    end
    starts = (1:step_samples:last_start)';
    n_windows = numel(starts);
    diagnostics.window_center_t = nan(n_windows, 1);
    diagnostics.h = nan(n_windows, 1);
    diagnostics.fm_hz = nan(n_windows, 1);
    diagnostics.fm_mhz = nan(n_windows, 1);
    diagnostics.dc_amplitude = nan(n_windows, 1);
    diagnostics.reconstruction_error = nan(n_windows, 1);
    diagnostics.evaluable_window_mask = false(n_windows, 1);

    for i = 1:n_windows
        idx = starts(i):starts(i) + n_window_samples - 1;
        diagnostics.window_center_t(i) = mean( ...
            diagnostics.envelope_t(idx([1 end])));
        if ~all(diagnostics.envelope_evaluable_mask(idx)) || ...
                any(~isfinite(diagnostics.envelope(idx)))
            continue;
        end
        estimate = estimate_matrix_pencil_modulation( ...
            diagnostics.envelope(idx), cfg.resample_hz);
        if ~estimate.evaluable
            continue;
        end
        diagnostics.evaluable_window_mask(i) = true;
        diagnostics.h(i) = estimate.h;
        diagnostics.fm_hz(i) = estimate.fm_hz;
        diagnostics.fm_mhz(i) = 1000 * estimate.fm_hz;
        diagnostics.dc_amplitude(i) = estimate.dc_amplitude;
        diagnostics.reconstruction_error(i) = estimate.reconstruction_error;
    end

    diagnostics.pathological_window_mask = classify_guyot_modulation( ...
        diagnostics.h, diagnostics.fm_hz, ...
        diagnostics.evaluable_window_mask, cfg.h_threshold, cfg.fm_band_hz);
    [diagnostics.evaluable_time_mask, diagnostics.pathological_time_mask] = ...
        window_estimates_to_time_masks( ...
            diagnostics.envelope_t, diagnostics.window_center_t, ...
            diagnostics.evaluable_window_mask, ...
            diagnostics.pathological_window_mask);
    single = combine_periodic_belt_evidence( ...
        diagnostics.envelope_t, diagnostics.evaluable_time_mask, ...
        diagnostics.pathological_time_mask, ...
        false(size(diagnostics.envelope_t)), ...
        false(size(diagnostics.envelope_t)), cfg.min_zone_sec, N, fs);
    diagnostics.candidate_mask = single.candidate_mask;
    diagnostics.events = single.events;
    diagnostics.available = any(diagnostics.evaluable_window_mask);
end

function [evaluable_time, pathological_time] = window_estimates_to_time_masks( ...
    t_sec, center_t, evaluable_window, pathological_window)
% WINDOW_ESTIMATES_TO_TIME_MASKS Use nearest-center support only between centers.

    evaluable_time = false(size(t_sec));
    pathological_time = false(size(t_sec));
    if isempty(center_t)
        return;
    end
    supported = t_sec >= center_t(1) & t_sec <= center_t(end);
    if isscalar(center_t)
        [~, index] = min(abs(t_sec - center_t));
        evaluable_time(index) = evaluable_window;
        pathological_time(index) = pathological_window & evaluable_window;
        return;
    end
    evaluable_time(supported) = interp1( ...
        center_t, double(evaluable_window), t_sec(supported), 'nearest') > 0.5;
    pathological_time(supported) = interp1( ...
        center_t, double(pathological_window), t_sec(supported), 'nearest') > 0.5;
    pathological_time = pathological_time & evaluable_time;
end

function diagnostics = empty_guyot_belt(recording_end_t, cfg)
% EMPTY_GUYOT_BELT Return one stable per-belt Guyot diagnostic schema.

    envelope_t = (0:1 / cfg.resample_hz:recording_end_t)';
    diagnostics = struct( ...
        'available', false, ...
        'method', 'MAGMA adaptation of Guyot et al. 2020', ...
        'reference_doi', '10.1371/journal.pone.0221191', ...
        'breath_t', [], ...
        'canonical_breath_amp', [], ...
        'median_ibi_sec', NaN, ...
        'envelope_t', envelope_t, ...
        'envelope', nan(size(envelope_t)), ...
        'envelope_evaluable_mask', false(size(envelope_t)), ...
        'long_gap_mask', false(size(envelope_t)), ...
        'window_center_t', [], ...
        'h', [], ...
        'fm_hz', [], ...
        'fm_mhz', [], ...
        'dc_amplitude', [], ...
        'reconstruction_error', [], ...
        'evaluable_window_mask', false(0, 1), ...
        'pathological_window_mask', false(0, 1), ...
        'evaluable_time_mask', false(size(envelope_t)), ...
        'pathological_time_mask', false(size(envelope_t)), ...
        'candidate_mask', false(size(envelope_t)), ...
        'events', empty_events());
end

function cfg = validate_guyot_config(cfg)
% VALIDATE_GUYOT_CONFIG Validate published settings and derive the step.

    required = {'resample_hz', 'window_sec', 'overlap_fraction', ...
        'h_threshold', 'fm_band_hz', 'min_zone_sec', 'gap_factor'};
    if ~isstruct(cfg) || ~all(isfield(cfg, required))
        error('MAGMA:Periodic:InvalidGuyotConfig', ...
            'config.periodic.guyot is incomplete.');
    end
    positive_scalars = {'resample_hz', 'window_sec', 'min_zone_sec'};
    for i = 1:numel(positive_scalars)
        value = cfg.(positive_scalars{i});
        if ~isscalar(value) || ~isfinite(value) || value <= 0
            error('MAGMA:Periodic:InvalidGuyotConfig', ...
                'config.periodic.guyot.%s must be positive.', positive_scalars{i});
        end
    end
    if ~isscalar(cfg.overlap_fraction) || ~isfinite(cfg.overlap_fraction) || ...
            cfg.overlap_fraction < 0 || cfg.overlap_fraction >= 1
        error('MAGMA:Periodic:InvalidGuyotConfig', ...
            'config.periodic.guyot.overlap_fraction must be in [0,1).');
    end
    if ~isscalar(cfg.gap_factor) || ~isfinite(cfg.gap_factor) || ...
            cfg.gap_factor <= 1
        error('MAGMA:Periodic:InvalidGuyotConfig', ...
            'config.periodic.guyot.gap_factor must exceed one.');
    end
    cfg.fm_band_hz = cfg.fm_band_hz(:)';
    classify_guyot_modulation([], [], false(0, 1), ...
        cfg.h_threshold, cfg.fm_band_hz);
    cfg.step_sec = cfg.window_sec * (1 - cfg.overlap_fraction);
end
