function [events, candidate_events] = detect_shallow_breathing(data, resp_features, config)
% DETECT_SHALLOW_BREATHING Localize consecutive shallow breaths as events.
% Each internal breath whose session-normalized excursion lies within the
% configured band contributes its complete trough-to-trough cycle. Touching
% cycles merge before the minimum-duration rule is applied. candidate_events
% retains every merged localized interval, including rejected short runs.

    events = empty_events();
    N = size(data, 1);
    t_grid = resp_features.time_sec;
    lungs = resp_features.lungs;
    diaph = resp_features.diaph;
    candidate_events = empty_candidate_events();

    if ~lungs.session_amplitude_available && ~diaph.session_amplitude_available
        log_message(config, 1, ...
            ['Skipping shallow detection: no valid respiratory belt with ' ...
             'usable breath amplitudes.']);
        return;
    end

    [events_lungs, candidates_lungs, localized_lungs_events] = ...
        localize_breath_amplitude_events( ...
        lungs, N, config.fs, 'shallow_breathing_lungs', ...
        'amplitude_band', config.shallow.amp_ratio_low, config.shallow.amp_ratio_high, ...
        config.shallow.min_dur_sec, 'lungs');

    [events_diaph, candidates_diaph, localized_diaph_events] = ...
        localize_breath_amplitude_events( ...
        diaph, N, config.fs, 'shallow_breathing_diaph', ...
        'amplitude_band', config.shallow.amp_ratio_low, config.shallow.amp_ratio_high, ...
        config.shallow.min_dur_sec, 'diaph');

    events = merge_events({events_lungs, events_diaph});
    localized_lungs = events_to_grid_mask(localized_lungs_events, t_grid);
    localized_diaph = events_to_grid_mask(localized_diaph_events, t_grid);
    candidate_events = [candidates_lungs; candidates_diaph];

    if config.shallow.do_plot
        opts = struct( ...
            'figure_title', 'SHALLOW BREATHING', ...
            'event_name', 'Shallow breathing', ...
            'lower_ratio', config.shallow.amp_ratio_low, ...
            'upper_ratio', config.shallow.amp_ratio_high, ...
            'localized_mask_lungs', localized_lungs, ...
            'localized_mask_diaph', localized_diaph, ...
            'output_name', 'shallow_breathing');
        plot_amplitude_state_diagnostic( ...
            resp_features, events_lungs, events_diaph, config, opts);
    end
end
