function [events, candidate_events] = detect_deep_breathing(data, resp_features, config)
% DETECT_DEEP_BREATHING Localize consecutive high-amplitude breaths as events.
% Each internal breath at or above the session-normalized threshold contributes
% its complete trough-to-trough cycle. Touching cycles merge before the
% minimum-duration rule is applied. candidate_events retains every merged
% localized interval, including rejected short runs.

    events = empty_events();
    N = size(data, 1);
    t_grid = resp_features.time_sec;
    lungs = resp_features.lungs;
    diaph = resp_features.diaph;
    candidate_events = empty_candidate_events();

    if ~lungs.session_amplitude_available && ~diaph.session_amplitude_available
        fprintf('Skipping deep detection: no valid respiratory belt with usable breath amplitudes.\n');
        return;
    end

    [events_lungs, candidates_lungs, localized_lungs_events] = ...
        localize_breath_amplitude_events( ...
        lungs, N, config.fs, 'deep_breathing_lungs', ...
        'amplitude_ge', config.deep.amp_ratio_thr, NaN, ...
        config.deep.min_dur_sec, 'lungs');
    [events_diaph, candidates_diaph, localized_diaph_events] = ...
        localize_breath_amplitude_events( ...
        diaph, N, config.fs, 'deep_breathing_diaph', ...
        'amplitude_ge', config.deep.amp_ratio_thr, NaN, ...
        config.deep.min_dur_sec, 'diaph');
    events = merge_events({events_lungs, events_diaph});
    localized_lungs = events_to_grid_mask(localized_lungs_events, t_grid);
    localized_diaph = events_to_grid_mask(localized_diaph_events, t_grid);
    candidate_events = [candidates_lungs; candidates_diaph];

    if config.deep.do_plot
        opts = struct( ...
            'figure_title', 'DEEP BREATHING', ...
            'event_name', 'Deep breathing', ...
            'lower_ratio', config.deep.amp_ratio_thr, ...
            'localized_mask_lungs', localized_lungs, ...
            'localized_mask_diaph', localized_diaph, ...
            'output_name', 'deep_breathing');
        plot_amplitude_state_diagnostic( ...
            resp_features, events_lungs, events_diaph, config, opts);
    end
end
