function tests = test_group_respiratory_reference_summary
% Verify the existing group table exposes the compact Phase 2A diagnostics.
    tests = functiontests(localfunctions);
end

function testSavedRespiratoryReferenceIsSummarized(testCase)
    results_root = tempname;
    subject_dir = fullfile(results_root, 'Sub5_M2');
    mkdir(subject_dir);
    cleanup_dir = onCleanup(@() rmdir(results_root, 's'));

    subject = 5;
    measure = 2;
    mask_automatic = false(100, 2);
    mask_automatic(21:60, 2) = true;
    % Historical v2 names deliberately exercise semantic (not positional)
    % mapping into the canonical group columns.
    label_names = {'shallowB', 'deepB'};
    config = struct('fs', 200);
    resp_ref = synthetic_saved_reference();
    resp_features = struct( ...
        'time_sec', (0:2)', ...
        'diaph', struct( ...
            'rate_slow_window_bpm', [10; 12; 14], ...
            'irregularity', struct('robust_cov', [0.1; 0.2; 0.3])), ...
        'thoracoabdominal_balance', struct( ...
            'thoracic_to_abdominal_ratio', [1; 2; 3], ...
            'thoracic_dominance_log_ratio', log([1; 2; 3]), ...
            'thoracic_relative_fraction', [0.5; 0.6; 0.7]));
    detector_diagnostics = struct( ...
        'async', struct('phase_coherence_mid', [0.7; 0.8; 0.9]), ...
        'csr', struct('eami', struct('lungs', ...
            struct('eami', [0.4; 0.6; 0.8]))));
    label_evidence_summary_automatic = struct( ...
        'version', 'test', 'deep', struct( ...
            'available', true, 'median_ratio_lungs', 1.4));
    label_evidence_summary_reviewed = struct( ...
        'version', 'test', 'deep', struct( ...
            'available', true, 'median_ratio_lungs', 1.5));
    save(fullfile(subject_dir, 'Sub5_M2_labels.mat'), ...
        'subject', 'measure', 'mask_automatic', 'label_names', 'config', ...
        'resp_ref', 'resp_features', 'detector_diagnostics', ...
        'label_evidence_summary_automatic', ...
        'label_evidence_summary_reviewed');

    group_table = build_group_label_table(results_root);

    verifyEqual(testCase, height(group_table), 1);
    verifyEqual(testCase, group_table.subject, 5);
    verifyEqual(testCase, group_table.measurement, 2);
    verifyEqual(testCase, group_table.lungs_start_end_ratio, 0.60, 'AbsTol', eps);
    verifyEqual(testCase, group_table.lungs_change_detected, 1);
    verifyEqual(testCase, group_table.lungs_change_t, 420);
    verifyEqual(testCase, group_table.lungs_change_ratio, 0.58, 'AbsTol', eps);
    verifyEqual(testCase, string(group_table.lungs_quality), "good");
    verifyEqual(testCase, string(group_table.diaph_quality), "good");
    verifyEqual(testCase, string(group_table.change_pattern), "both_similar");
    verifyEqual(testCase, group_table.lungs_session_reference_raw_units, 1.1, 'AbsTol', eps);
    verifyEqual(testCase, group_table.lungs_global_reference_raw_units, 0.9, 'AbsTol', eps);
    verifyEqual(testCase, group_table.lungs_global_to_session_ratio, 0.9/1.1, 'AbsTol', eps);
    verifyEqual(testCase, string(group_table.lungs_reference_quality), "step_candidate");
    verifyEqual(testCase, string(group_table.lungs_reference_action), "retain_data_no_correction");
    verifyEqual(testCase, group_table.label_deep_duration_sec, 40/200, 'AbsTol', eps);
    verifyEqual(testCase, group_table.label_deep_fraction, 0.40, 'AbsTol', eps);
    verifyEqual(testCase, group_table.label_deep_available, 1);
    verifyEqual(testCase, group_table.label_thoracic_available, 0);
    verifyTrue(testCase, isnan(group_table.label_thoracic_duration_sec));
    verifyTrue(testCase, isnan(group_table.label_thoracic_fraction));
    verifyTrue(testCase, isnan(group_table.events_thoracic_count));
    verifyEqual(testCase, ...
        group_table.trace_breathing_rate_slow_window_bpm_diaph_median, 12);
    verifyEqual(testCase, ...
        group_table.trace_resp_asynchrony_phase_coherence_mid_median, 0.8, ...
        'AbsTol', eps);
    verifyEqual(testCase, group_table.trace_eami_lungs_median, 0.6, ...
        'AbsTol', eps);
    verifyEqual(testCase, ...
        group_table.evidence_automatic_deep_median_ratio_lungs, 1.4);
    verifyEqual(testCase, ...
        group_table.evidence_reviewed_deep_median_ratio_lungs, 1.5);

    dictionary_file = fullfile(results_root, 'group_analysis', ...
        'group_measure_comparability.csv');
    verifyTrue(testCase, isfile(dictionary_file));
    dictionary = readtable(dictionary_file, 'Delimiter', ',', ...
        'TextType', 'string', 'VariableNamingRule', 'preserve');
    verifyTrue(testCase, any(dictionary.measure_family == "respiratory_rate" & ...
        dictionary.comparability == "absolute_comparable_across_subjects"));
    verifyTrue(testCase, any(dictionary.measure_family == "belt_amplitude_ratio" & ...
        dictionary.comparability == "within_record_normalized"));
    verifyTrue(testCase, any(dictionary.measure_family == "thoracic_to_abdominal_ratio" & ...
        dictionary.comparability == "within_record_normalized"));
    verifyTrue(testCase, any(dictionary.measure_family == "raw_belt_amplitude" & ...
        dictionary.comparability == "not_safely_comparable_across_subjects"));
end

function testGroupDiagnosticOverviewUsesAuthoritativeNestedPaths(testCase)
    repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    source = fileread(fullfile(repo_root, 'src', 'group', ...
        'plot_group_diagnostic_overview.m'));
    required = { ...
        'diaph.rate_slow_window_bpm', ...
        'diaph.irregularity.robust_cov', ...
        'async.phase_coherence_mid', ...
        'thoracoabdominal_balance.thoracic_to_abdominal_ratio', ...
        'thoracoabdominal_balance.thoracic_dominance_log_ratio', ...
        'thoracoabdominal_balance.thoracic_relative_fraction', ...
        'csr.eami.lungs.eami', ...
        'trace_breathing_rate_slow_window_bpm_diaph', ...
        'trace_eami_lungs'};
    for i = 1:numel(required)
        verifyTrue(testCase, contains(source, required{i}));
    end
    verifyFalse(testCase, contains(source, ['diagnostic_' 'signals']));
end

function testAssessedZeroLabelsRemainDistinctFromUnavailable(testCase)
    results_root = tempname;
    subject_dir = fullfile(results_root, 'Sub42_M3');
    mkdir(subject_dir);
    cleanup_dir = onCleanup(@() rmdir(results_root, 's'));

    current = get_config();
    subject = 42;
    measure = 3;
    mask_automatic = false(100, numel(current.labels));
    label_names = {current.labels.short};
    label_available = true(1, numel(label_names));
    config = struct('fs', 10);
    save(fullfile(subject_dir, 'Sub42_M3_labels.mat'), ...
        'subject', 'measure', 'mask_automatic', 'label_names', ...
        'label_available', 'config');

    group_table = build_group_label_table(results_root);
    verifyEqual(testCase, group_table.label_deep_available, 1);
    verifyEqual(testCase, group_table.label_deep_duration_sec, 0);
    verifyEqual(testCase, group_table.label_deep_fraction, 0);
    verifyEqual(testCase, group_table.label_thoracic_available, 1);
    verifyEqual(testCase, group_table.label_thoracic_duration_sec, 0);
    verifyEqual(testCase, group_table.label_thoracic_fraction, 0);
    verifyEqual(testCase, group_table.events_thoracic_count, 0);
end

function testEventsAndCandidatesUseSemanticIdentityAndIndices(testCase)
    results_root = tempname;
    subject_dir = fullfile(results_root, 'Sub8_M1');
    mkdir(subject_dir);
    cleanup_dir = onCleanup(@() rmdir(results_root, 's'));

    current = get_config();
    subject = 8;
    measure = 1;
    label_names = {current.labels.short};
    label_available = true(1,11);
    mask_automatic = false(20,11);
    config = struct('fs',10);
    events_automatic = struct('type','rapidB','start_idx',1,'end_idx',10, ...
        'start_t',50,'end_t',60,'duration',999);
    record = struct('start_idx',11,'end_idx',290, ...
        'start_t',1,'end_t',29,'duration',28,'belt','lungs', ...
        'accepted',false,'rejection_reason','too_short', ...
        'uncertainty_sec',1);
    candidate_events = struct('rapid', record);
    save(fullfile(subject_dir,'Sub8_M1_labels.mat'), 'subject','measure', ...
        'label_names','label_available','mask_automatic','events_automatic', ...
        'candidate_events','config');

    build_group_label_table(results_root);
    event_table = readtable(fullfile(results_root,'group_analysis', ...
        'cohort_event_durations.csv'),'TextType','string');
    verifyEqual(testCase,event_table.label,"rapid");
    verifyEqual(testCase,event_table.duration_sec,1,'AbsTol',eps);
    candidate_table = readtable(fullfile(results_root,'group_analysis', ...
        'cohort_candidate_events.csv'),'TextType','string');
    verifyEqual(testCase, candidate_table.Properties.VariableNames, ...
        {'subject','measurement','label','belt','start_t','end_t', ...
         'duration','accepted','rejection_reason','uncertainty_sec'});
    verifyEqual(testCase,candidate_table.label,"rapid");
    verifyEqual(testCase,candidate_table.duration,28);
    verifyFalse(testCase,candidate_table.accepted);
    verifyEqual(testCase,candidate_table.rejection_reason,"too_short");
    qc_data = load(fullfile(results_root,'group_analysis','cohort_qc_summary.mat'));
    rapid_row = qc_data.cohort_qc.by_label.label == "rapid";
    verifyEqual(testCase, ...
        qc_data.cohort_qc.by_label.rejected_candidate_count(rapid_row),1);
end

function resp_ref = synthetic_saved_reference()
    lungs = struct( ...
        'session', struct('value', 1.1, 'n_breaths', 80, 'available', true), ...
        'global', struct('value', 0.9, 'n_breaths', 300, 'available', true), ...
        'global_to_session_ratio', 0.9/1.1, ...
        'reference_quality', 'step_candidate', ...
        'reference_action', 'retain_data_no_correction', ...
        'end_to_start_ratio', 0.60, ...
        'change_detected', true, ...
        'change_t', 420, ...
        'change_ratio', 0.58, ...
        'quality', 'good');
    diaph = struct( ...
        'session', struct('value', 0.8, 'n_breaths', 82, 'available', true), ...
        'global', struct('value', 0.75, 'n_breaths', 302, 'available', true), ...
        'global_to_session_ratio', 0.75/0.8, ...
        'reference_quality', 'good', ...
        'reference_action', 'retain_data_no_correction', ...
        'end_to_start_ratio', 0.62, ...
        'change_detected', true, ...
        'change_t', 426, ...
        'change_ratio', 0.60, ...
        'quality', 'good');
    resp_ref = struct('lungs', lungs, 'diaph', diaph, ...
        'change_pattern', 'both_similar');
end
