function tests = test_example_pipeline_smoke
% Test I: non-interactive preprocessing and breath extraction smoke test.
    tests = functiontests(localfunctions);
end

function testExampleRecordingRunsAtMasterRate(testCase)
    this_file = mfilename('fullpath');
    repo_root = fileparts(fileparts(fileparts(this_file)));
    example_file = fullfile(repo_root, 'example_data', ...
        'ECG1_ECG2_SpO2_RespL_BP_RespD_fs200_Sub42_Pom1_DeTr_Norm.dat');
    assumeTrue(testCase, isfile(example_file), 'Example recording is not available.');

    output_dir = tempname;
    mkdir(output_dir);
    cleanup_dir = onCleanup(@() rmdir(output_dir, 's'));
    config = make_test_config(output_dir);
    config.subject = 42;
    config.measure = 1;
    config.overwrite_features = true;

    n_rows = 120 * config.fs;
    data_raw = read_first_rows(example_file, numel(config.data_columns), n_rows);
    verifyEqual(testCase, size(data_raw,2), numel(config.data_columns));

    [data, config] = preprocess_data(data_raw, config);
    resp_cycles = load_or_extract_respiratory_cycles(data, config);

    verifySize(testCase, data, size(data_raw));
    verifyEqual(testCase, config.fs, 200);
    removed_rate_field = ['new_' 'fs'];
    verifyFalse(testCase, isfield(config, removed_rate_field));
    verifyEqual(testCase, numel(resp_cycles.lungs.x0), size(data_raw,1));
    verifyEqual(testCase, numel(resp_cycles.diaph.x0), size(data_raw,1));

    % End-to-end smoke: common evidence plus every independent detector. The
    % short excerpt may lack the protocol session interval; unavailable
    % amplitude evidence must skip cleanly without changing other streams.
    session_reference = get_session_reference_interval(size(data, 1), config);
    resp_ref = compute_respiratory_reference( ...
        resp_cycles, session_reference, config);
    spo2_ref = compute_spo2_reference(data, session_reference, config);
    resp_features = compute_respiratory_features( ...
        data, resp_cycles, resp_ref, config);

    events_ShB = detect_shallow_breathing(data, resp_features, config);
    events_DeB = detect_deep_breathing(data, resp_features, config);
    events_TDB = detect_thoracic_dominant_breathing(data, resp_features, config);
    events_IrB = detect_irregular_breathing(data, resp_features, config);
    events_SlB = detect_slow_breathing(data, resp_features, config);
    events_RaB = detect_rapid_breathing(data, resp_features, config);
    [events_ReA, diagnostics_ReA] = detect_respiratory_asynchrony( ...
        data, session_reference, resp_cycles, config);
    [events_Des, diagnostics_Des] = detect_desaturation( ...
        data, spo2_ref, session_reference, config);
    [events_Apn, diagnostics_Apn] = detect_apnea( ...
        data, resp_features, session_reference, config);
    [events_Sigh, diagnostics_Sigh, sigh_review] = detect_sigh( ...
        data, resp_features, resp_cycles, spo2_ref, session_reference, ...
        diagnostics_Des, config);
    [events_CSR, diagnostics_CSR] = detect_periodic_breathing( ...
        data, resp_cycles, config);

    events = normalize_event_types_and_meta(merge_events({ ...
        events_ShB, events_IrB, events_SlB, events_RaB, events_ReA, ...
        events_Des, events_Apn, events_Sigh, events_CSR, events_DeB, events_TDB}), ...
        config.fs);
    [mask, label_names] = events_to_time_mask(events, size(data,1), config);
    [label_available, reasons] = compute_label_availability( ...
        label_names, resp_features, diagnostics_Des, diagnostics_ReA, ...
        diagnostics_Apn, diagnostics_Sigh, diagnostics_CSR);
    diagnostic = compute_label_diagnostic_signals( ...
        resp_features, spo2_ref, diagnostics_Des, config, diagnostics_ReA, ...
        diagnostics_Apn, diagnostics_Sigh, diagnostics_CSR);
    detector_diagnostics = struct('respiratory_asynchrony', diagnostics_ReA, ...
        'desaturation', diagnostics_Des, ...
        'apnea', diagnostics_Apn, 'sigh', diagnostics_Sigh, ...
        'periodic_breathing', diagnostics_CSR);
    burden = compute_recording_label_burden( ...
        mask, label_names, label_available, events, config.fs);
    overlaps = compute_label_overlap_summary( ...
        mask, label_names, label_available, config.fs);
    evidence = build_label_evidence_summary( ...
        label_names, label_available, reasons, resp_features, diagnostic, ...
        detector_diagnostics, burden);
    phenotypes = build_db_phenotype_evidence(burden, overlaps, evidence);

    weak_sets = struct('shallow',events_ShB,'deep',events_DeB, ...
        'thoracic',events_TDB,'irregular',events_IrB,'slow',events_SlB, ...
        'rapid',events_RaB,'async',events_ReA,'desat',events_Des, ...
        'apnea',events_Apn,'csr',events_CSR);
    [reviewed_sets, manual_info] = manual_edit_label_events(data,config,weak_sets);
    annotations = assemble_annotation_layers(weak_sets,reviewed_sets, ...
        manual_info,sigh_review,size(data,1),config);
    [assessable, assessability_info] = compute_label_assessable_mask( ...
        size(data,1),label_names,label_available,diagnostics_Des,diagnostics_ReA,config);

    weak_burden = compute_recording_label_burden(annotations.mask_weak, ...
        label_names,label_available,annotations.events_weak,config.fs,assessable);
    weak_overlap = compute_label_overlap_summary(annotations.mask_weak, ...
        label_names,label_available,config.fs,assessable);
    weak_evidence = build_label_evidence_summary(label_names,label_available, ...
        reasons,resp_features,diagnostic,detector_diagnostics,weak_burden);
    [reviewed_assessable, reviewed_available, reviewed_reasons] = ...
        compute_reviewed_label_availability(label_available, reasons, ...
            assessable, annotations.gold_review_mask);
    reviewed_burden = compute_recording_label_burden(annotations.mask_reviewed, ...
        label_names,reviewed_available,annotations.events_reviewed,config.fs, ...
        reviewed_assessable);
    reviewed_overlap = compute_label_overlap_summary(annotations.mask_reviewed, ...
        label_names,reviewed_available,config.fs,reviewed_assessable);
    reviewed_evidence = build_label_evidence_summary(label_names, ...
        reviewed_available,reviewed_reasons,resp_features,diagnostic, ...
        detector_diagnostics,reviewed_burden);
    phenotype_bundle = build_db_phenotype_evidence_bundle(weak_burden, ...
        weak_overlap,weak_evidence,reviewed_burden,reviewed_overlap, ...
        reviewed_evidence);

    export_results = struct('subject',config.subject,'measure',config.measure, ...
        'config',config,'resp_cycles',resp_cycles, ...
        'resp_features',resp_features, ...
        'desaturation_diagnostics',diagnostics_Des, ...
        'session_reference',session_reference,'resp_ref',resp_ref, ...
        'spo2_ref',spo2_ref, ...
        'label_names',{label_names},'label_available',label_available, ...
        'label_availability_reason',{reasons}, ...
        'label_assessable_mask',assessable, ...
        'label_reviewed_available',reviewed_available, ...
        'label_reviewed_availability_reason',{reviewed_reasons}, ...
        'label_reviewed_assessable_mask',reviewed_assessable, ...
        'mask_weak',annotations.mask_weak, ...
        'mask_reviewed',annotations.mask_reviewed, ...
        'gold_review_mask',annotations.gold_review_mask, ...
        'review_status',{annotations.review_status}, ...
        'events_weak',annotations.events_weak, ...
        'events_reviewed',annotations.events_reviewed, ...
        'label_burden_weak',weak_burden, ...
        'label_burden_reviewed',reviewed_burden, ...
        'label_overlap_summary_weak',weak_overlap, ...
        'label_overlap_summary_reviewed',reviewed_overlap, ...
        'db_phenotype_evidence',phenotype_bundle, ...
        'diagnostic_signals',diagnostic, ...
        'detector_diagnostics',detector_diagnostics, ...
        'label_schema_version',config.label_schema_version, ...
        'annotation_schema_version',annotations.version, ...
        'export_schema_version','magma_ml_hdf5_v2', ...
        'upstream_input_preprocessing','external / not fully documented');
    hdf5_file = fullfile(output_dir,'example_pipeline.h5');
    export_results_hdf5(hdf5_file,export_results,data_raw,data);

    verifyEqual(testCase, size(mask,1), size(data,1));
    verifyEqual(testCase, size(mask,2), numel(label_names));
    verifyEqual(testCase, resp_features.resp.lungs.peak_idx, resp_cycles.lungs.peak_idx);
    verifyEqual(testCase, diagnostic.time_sec, resp_features.resp.time_sec);
    verifyEqual(testCase, numel(reasons), 11);
    verifyEqual(testCase, phenotypes.version, 'magma_db_phenotype_evidence_v1');
    verifyEqual(testCase, annotations.events_weak, events);
    verifyEqual(testCase, annotations.mask_weak, mask);
    verifyFalse(testCase, any(annotations.gold_review_mask(:)));
    verifySize(testCase, assessable, size(mask));
    verifyEqual(testCase, assessability_info.version, 'label_assessability_v1');
    verifyEqual(testCase, read_hdf5_text(hdf5_file,'/labels/names'),label_names);
    verifyEqual(testCase, logical(h5read(hdf5_file,'/labels/weak_mask')),mask);
    verifyEqual(testCase, h5read(hdf5_file,'/meta/fs'),config.fs);
    verifyEqual(testCase, read_hdf5_text(hdf5_file, ...
        '/session_reference/reference_schema_version'), ...
        {'session_physiological_reference_v1'});
end

function data = read_first_rows(filename, n_columns, n_rows)
    fid = fopen(filename, 'r');
    if fid < 0
        error('Could not open example recording: %s', filename);
    end
    cleanup_file = onCleanup(@() fclose(fid));
    format = repmat('%f', 1, n_columns);
    values = textscan(fid, format, n_rows, 'CollectOutput', true);
    data = values{1};
end
