function bundle = build_db_phenotype_evidence_bundle( ...
    automatic_burden, automatic_overlap, automatic_evidence, ...
    reviewed_burden, reviewed_overlap, reviewed_evidence)
% BUILD_DB_PHENOTYPE_EVIDENCE_BUNDLE Build parallel automatic/reviewed profiles.
% Each input triplet is label burden, overlap, and detector-evidence summary for
% one annotation layer. bundle fields are version; automatic and reviewed
% phenotype evidence with explicit annotation/detector scopes; event-specific
% measures follow each layer while full-record detector QC may be shared.

    bundle = struct();
    bundle.version = 'magma_db_phenotype_evidence_bundle_v2';
    bundle.automatic = build_db_phenotype_evidence( ...
        automatic_burden, automatic_overlap, automatic_evidence, 'automatic_labels');
    bundle.reviewed = build_db_phenotype_evidence( ...
        reviewed_burden, reviewed_overlap, reviewed_evidence, 'reviewed_labels');
    bundle.automatic.annotation_scope = 'full_assessable_recording';
    bundle.automatic.detector_evidence_scope = ...
        'automatic_annotation_event_evidence_with_shared_detector_qc';
    bundle.reviewed.annotation_scope = 'explicitly_reviewed_and_assessable_regions';
    bundle.reviewed.detector_evidence_scope = ...
        'reviewed_annotation_event_evidence_with_shared_detector_qc';
    bundle.external_clinical_data = bundle.automatic.external_clinical_data;
    bundle.provenance_note = [ ...
        'automatic and reviewed profiles are descriptive signal-derived evidence; ' ...
        'external clinical data are not integrated and no profile is a diagnosis'];
end
