function evidence = build_db_phenotype_evidence( ...
    label_burden, overlaps, label_evidence)
% build_db_phenotype_evidence
% Prespecified MAGMA WP1 phenotype evidence. These five structures are not
% diagnoses, mutually exclusive classes, or additions to the label mask.

    evidence = struct();
    evidence.version = 'magma_db_phenotype_evidence_v1';
    evidence.levels = struct( ...
        'level_1', 'elementary weak physiological labels and evidence', ...
        'level_2', 'prespecified MAGMA DB phenotype evidence', ...
        'level_3', 'future data-driven phenotype discovery');

    hvs_measures = struct( ...
        'rapid_fraction', label_burden.by_label.rapidB.fraction, ...
        'deep_fraction', label_burden.by_label.deepB.fraction, ...
        'rapid_deep_overlap_fraction_of_rapid', ...
            overlaps.rapid_deep.fraction_of_a_overlapped_by_b, ...
        'rapid_deep_overlap_fraction_of_deep', ...
            overlaps.rapid_deep.fraction_of_b_overlapped_by_a, ...
        'median_rr_lungs', label_evidence.rapidB.median_rr_lungs, ...
        'median_rr_diaph', label_evidence.rapidB.median_rr_diaph, ...
        'median_deep_excursion_ratio_lungs', label_evidence.deepB.median_ratio_lungs, ...
        'median_deep_excursion_ratio_diaph', label_evidence.deepB.median_ratio_diaph);
    evidence.hyperventilation_syndrome = phenotype( ...
        'Hyperventilation syndrome', false, ...
        label_burden.by_label.rapidB.available || label_burden.by_label.deepB.available, ...
        hvs_measures, ...
        {'ETCO2_or_capnography', 'ventilation_relative_to_metabolic_demand', ...
         'cardiopulmonary_exercise_testing', 'clinical_assessment', ...
         'Nijmegen_Questionnaire'}, ...
        {'respiratory_pattern_support_only', ...
         'rapid_plus_deep_is_not_a_hyperventilation_diagnosis'});

    sigh_measures = struct( ...
        'sigh_count', label_burden.sigh_count, ...
        'sighs_per_15_min', label_burden.sighs_per_15_min, ...
        'irregular_fraction', label_burden.by_label.irregB.fraction, ...
        'deep_fraction', label_burden.by_label.deepB.fraction, ...
        'fraction_of_sigh_overlapping_irregular', ...
            overlaps.sigh_irregular.fraction_of_a_overlapped_by_b);
    evidence.periodic_deep_sighing = phenotype( ...
        'Periodic deep sighing', true, ...
        label_burden.by_label.sigh.available && label_burden.by_label.irregB.available, ...
        sigh_measures, {}, ...
        {'continuous_pattern_evidence_without_a_clinical_cutoff', ...
         'distinct_from_CSR_periodic_breathing'});

    thor_measures = struct( ...
        'thoracic_dominance_fraction', label_burden.by_label.thorDomB.fraction, ...
        'median_thoracic_to_abdominal_ratio', label_evidence.thorDomB.median_ratio, ...
        'median_log_ratio', label_evidence.thorDomB.median_log_ratio, ...
        'median_thoracic_relative_fraction', label_evidence.thorDomB.median_relative_fraction);
    evidence.thoracic_dominant_breathing = phenotype( ...
        'Thoracic-dominant breathing', true, ...
        label_burden.by_label.thorDomB.available, thor_measures, ...
        {'future_clinical_or_ergospirometric_validation'}, ...
        {'relative_within_record_change_from_independently_normalized_uncalibrated_belts', ...
         'not_calibrated_rib_cage_contribution'});

    evidence.forced_abdominal_expiration = phenotype( ...
        'Forced abdominal expiration', false, false, struct(), ...
        {'clinical_annotation_or_direct_abdominal_muscle_or_mechanical_evidence'}, ...
        {'belt_movement_cannot_establish_active_abdominal_muscle_recruitment', ...
         'future_kinematic_proxies_would_not_be_direct_muscle_evidence'});

    async_measures = struct( ...
        'asynchrony_fraction', label_burden.by_label.asyncB.fraction, ...
        'analysis_valid', label_evidence.asyncB.analysis_valid, ...
        'baseline_coherence', label_evidence.asyncB.baseline_coherence, ...
        'median_observed_coherence', label_evidence.asyncB.median_observed_coherence, ...
        'maximum_deviating_bins', label_evidence.asyncB.maximum_deviating_bins);
    evidence.thoracoabdominal_asynchrony = phenotype( ...
        'Thoraco-abdominal asynchrony', true, ...
        label_burden.by_label.asyncB.available, async_measures, ...
        {'clinical_validation'}, ...
        {'algorithmic_wavelet_coherence_evidence_not_clinical_diagnosis', ...
         'distinct_from_thoracic_dominance'});
end

function out = phenotype(name, assessable, available, measures, required, limitations)
    out = struct( ...
        'name', name, ...
        'assessable_from_current_signals', logical(assessable), ...
        'evidence_available', logical(available), ...
        'signal_derived_measures', measures, ...
        'required_external_clinical_data', {required}, ...
        'limitations', {limitations});
end
