function evidence = build_db_phenotype_evidence( ...
    label_burden, overlaps, label_evidence, source_provenance)
% BUILD_DB_PHENOTYPE_EVIDENCE Build compact continuous phenotype profiles.
% Inputs describe one automatic or reviewed annotation layer. Outputs organize
% prespecified DB evidence and respiratory-pattern evidence without diagnoses,
% binary phenotype-present flags, new thresholds, or duplicated time series.

    if nargin < 4 || isempty(source_provenance)
        source_provenance = 'automatic_labels';
    end
    source_provenance = char(string(source_provenance));

    evidence = struct();
    evidence.version = 'magma_db_phenotype_evidence_v2';
    evidence.source_provenance = source_provenance;
    evidence.external_clinical_data = empty_external_clinical_data();
    evidence.levels = struct( ...
        'level_1', 'elementary physiological labels and evidence', ...
        'level_2', 'continuous prespecified MAGMA DB phenotype evidence', ...
        'level_3', 'future data-driven phenotype discovery');

    rapid = burden_entry(label_burden, 'rapid');
    deep = burden_entry(label_burden, 'deep');
    sigh = burden_entry(label_burden, 'sigh');
    irregular = burden_entry(label_burden, 'irregular');
    thoracic = burden_entry(label_burden, 'thoracic');
    async = burden_entry(label_burden, 'async');
    apnea = burden_entry(label_burden, 'apnea');
    periodic = burden_entry(label_burden, 'periodic');
    shallow = burden_entry(label_burden, 'shallow');
    slow = burden_entry(label_burden, 'slow');
    desat = burden_entry(label_burden, 'desat');

    rapid_deep = overlap_entry(overlaps, 'rapid_deep');
    sigh_irregular = overlap_entry(overlaps, 'sigh_irregular');

    hyperventilation_measures = struct( ...
        'rapid_fraction', rapid.fraction, ...
        'deep_fraction', deep.fraction, ...
        'rapid_deep_overlap_duration_sec', ...
            metric(rapid_deep, 'overlap_duration_sec'), ...
        'rapid_deep_overlap_fraction_of_rapid', ...
            metric(rapid_deep, 'fraction_of_a_overlapped_by_b'), ...
        'rapid_deep_overlap_fraction_of_deep', ...
            metric(rapid_deep, 'fraction_of_b_overlapped_by_a'), ...
        'rapid_deep_event_count', ...
            metric(rapid_deep, 'overlap_event_count'), ...
        'median_rapid_deep_event_duration_sec', ...
            metric(rapid_deep, 'median_overlap_event_duration_sec'), ...
        'max_rapid_deep_event_duration_sec', ...
            metric(rapid_deep, 'max_overlap_event_duration_sec'), ...
        'median_respiratory_rate_lungs_bpm', ...
            label_metric(label_evidence, 'rapid', 'median_rr_lungs'), ...
        'median_respiratory_rate_diaph_bpm', ...
            label_metric(label_evidence, 'rapid', 'median_rr_diaph'), ...
        'median_relative_deep_excursion_lungs', ...
            label_metric(label_evidence, 'deep', 'median_ratio_lungs'), ...
        'median_relative_deep_excursion_diaph', ...
            label_metric(label_evidence, 'deep', 'median_ratio_diaph'));
    prespecified.hyperventilation_like = phenotype( ...
        'Hyperventilation-like respiratory pattern', false, ...
        rapid.available || deep.available, hyperventilation_measures, ...
        {'ETCO2_or_capnography', 'ventilation_relative_to_metabolic_demand', ...
         'cardiopulmonary_exercise_testing', 'clinical_assessment', ...
         'Nijmegen_Questionnaire'}, ...
        {'continuous_respiratory_pattern_evidence_not_a_diagnosis', ...
         'ventilation_and_CO2_are_not_measured', ...
         'rapid_plus_deep_does_not_establish_hyperventilation_syndrome'});

    periodic_sigh_measures = struct( ...
        'sigh_count', scalar_metric(label_burden, 'sigh_count'), ...
        'sighs_per_15_min', scalar_metric(label_burden, 'sighs_per_15_min'), ...
        'max_sighs_in_any_15_min_window', ...
            scalar_metric(label_burden, 'max_sighs_in_any_15_min_window'), ...
        'irregular_fraction', irregular.fraction, ...
        'deep_fraction', deep.fraction, ...
        'fraction_of_sigh_overlapping_irregular', ...
            metric(sigh_irregular, 'fraction_of_a_overlapped_by_b'), ...
        'median_inter_sigh_interval_sec', ...
            scalar_metric(label_burden, 'median_inter_sigh_interval_sec'), ...
        'minimum_inter_sigh_interval_sec', ...
            scalar_metric(label_burden, 'minimum_inter_sigh_interval_sec'));
    prespecified.periodic_deep_sighing = phenotype( ...
        'Periodic deep sighing', true, sigh.available, ...
        periodic_sigh_measures, {}, ...
        {'continuous_pattern_evidence_without_a_clinical_cutoff', ...
         'rolling_15_minimum_uses_canonical_sigh_event_times', ...
         'distinct_from_periodic_breathing_label'});

    thoracic_measures = event_measures(thoracic);
    thoracic_measures.thoracic_dominance_fraction = thoracic.fraction;
    thoracic_measures.median_thoracic_to_abdominal_ratio = ...
        label_metric(label_evidence, 'thoracic', 'median_ratio');
    thoracic_measures.median_log_ratio = ...
        label_metric(label_evidence, 'thoracic', 'median_log_ratio');
    thoracic_measures.median_thoracic_relative_fraction = ...
        label_metric(label_evidence, 'thoracic', 'median_relative_fraction');
    prespecified.thoracic_dominant_breathing = phenotype( ...
        'Thoracic-dominant breathing', true, thoracic.available, ...
        thoracic_measures, {'future_clinical_or_ergospirometric_validation'}, ...
        {'relative_within_record_change_from_independently_normalized_uncalibrated_belts', ...
         'not_calibrated_rib_cage_contribution'});

    prespecified.forced_abdominal_expiration = phenotype( ...
        'Forced abdominal expiration', false, false, struct(), ...
        {'clinical_annotation_or_direct_abdominal_muscle_or_mechanical_evidence'}, ...
        {'not_currently_assessable', ...
         'belt_movement_cannot_establish_active_abdominal_muscle_recruitment', ...
         'thoracic_dominance_is_not_used_as_a_proxy'});

    async_measures = event_measures(async);
    async_measures.asynchrony_fraction = async.fraction;
    async_measures.median_absolute_phase_deg = ...
        label_metric(label_evidence, 'async', 'median_absolute_phase_deg');
    async_measures.maximum_absolute_phase_deg = ...
        label_metric(label_evidence, 'async', 'maximum_absolute_phase_deg');
    async_measures.median_resultant_length = ...
        label_metric(label_evidence, 'async', 'median_resultant_length');
    async_measures.median_selected_resp_frequency_hz = ...
        label_metric(label_evidence, 'async', ...
            'median_selected_resp_frequency_hz');
    async_measures.median_expected_resp_frequency_hz = ...
        label_metric(label_evidence, 'async', ...
            'median_expected_resp_frequency_hz');
    async_measures.median_selected_to_expected_frequency_ratio = ...
        label_metric(label_evidence, 'async', ...
            'median_selected_to_expected_frequency_ratio');
    async_measures.phase_offset_qc = ...
        label_metric(label_evidence, 'async', 'phase_offset_qc', struct());
    async_measures.primary_method = ...
        label_metric(label_evidence, 'async', 'primary_method', '');
    async_measures.legacy_coherence_complementary = struct( ...
        'reference_coherence', label_metric( ...
            label_evidence, 'async', 'reference_coherence', struct()), ...
        'median_observed_coherence', label_metric( ...
            label_evidence, 'async', 'median_observed_coherence', struct()), ...
        'maximum_deviating_bins', label_metric( ...
            label_evidence, 'async', 'maximum_deviating_bins'));
    prespecified.thoracoabdominal_asynchrony = phenotype( ...
        'Thoraco-abdominal asynchrony', true, async.available, ...
        async_measures, {'clinical_validation'}, ...
        {'algorithmic_wavelet_asynchrony_evidence_not_clinical_diagnosis', ...
         'legacy_coherence_is_complementary_diagnostic_evidence', ...
         'distinct_from_thoracic_dominance'});

    apnea_measures = event_measures(apnea);
    apnea_measures = add_label_metrics(apnea_measures, label_evidence, 'apnea', { ...
        'amplitude_path_available', 'raw_excursion_path_available', ...
        'amplitude_support_belts', 'raw_excursion_support_belts', ...
        'amplitude_supported_fraction', 'raw_fallback_supported_fraction', ...
        'combined_supported_fraction', 'median_amplitude_ratio_lungs', ...
        'median_amplitude_ratio_diaph', 'minimum_amplitude_ratio_lungs', ...
        'minimum_amplitude_ratio_diaph', ...
        'median_raw_excursion_ratio_lungs', ...
        'median_raw_excursion_ratio_diaph', ...
        'minimum_raw_excursion_ratio_lungs', ...
        'minimum_raw_excursion_ratio_diaph'});
    patterns.apneic_breathing = respiratory_pattern( ...
        'Apneic breathing', apnea.available, apnea_measures, ...
        {'signal_derived_apnea_pattern_not_a_clinical_diagnosis'});

    periodic_measures = event_measures(periodic);
    periodic_measures = add_label_metrics(periodic_measures, label_evidence, ...
        'periodic', {'primary_method', 'eami_available', 'eami_median', ...
        'eami_max', 'guyot_available', 'guyot_median_h', 'guyot_max_h', ...
        'guyot_median_fm_hz'});
    patterns.periodic_breathing = respiratory_pattern( ...
        'Periodic breathing', periodic.available, periodic_measures, ...
        {'method_specific_values_are_named_and_not_interchangeable'});

    shallow_measures = event_measures(shallow);
    shallow_measures.median_relative_excursion_lungs = ...
        label_metric(label_evidence, 'shallow', 'median_ratio_lungs');
    shallow_measures.median_relative_excursion_diaph = ...
        label_metric(label_evidence, 'shallow', 'median_ratio_diaph');
    shallow_measures.minimum_relative_excursion_lungs = ...
        label_metric(label_evidence, 'shallow', 'minimum_ratio_lungs');
    shallow_measures.minimum_relative_excursion_diaph = ...
        label_metric(label_evidence, 'shallow', 'minimum_ratio_diaph');
    patterns.shallow_breathing = respiratory_pattern( ...
        'Shallow breathing', shallow.available, shallow_measures, {});

    deep_measures = event_measures(deep);
    deep_measures.median_relative_excursion_lungs = ...
        label_metric(label_evidence, 'deep', 'median_ratio_lungs');
    deep_measures.median_relative_excursion_diaph = ...
        label_metric(label_evidence, 'deep', 'median_ratio_diaph');
    deep_measures.maximum_relative_excursion_lungs = ...
        label_metric(label_evidence, 'deep', 'maximum_ratio_lungs');
    deep_measures.maximum_relative_excursion_diaph = ...
        label_metric(label_evidence, 'deep', 'maximum_ratio_diaph');
    patterns.deep_breathing = respiratory_pattern( ...
        'Deep breathing', deep.available, deep_measures, {});

    slow_measures = event_measures(slow);
    slow_measures.median_respiratory_rate_lungs_bpm = ...
        label_metric(label_evidence, 'slow', 'median_rr_lungs');
    slow_measures.median_respiratory_rate_diaph_bpm = ...
        label_metric(label_evidence, 'slow', 'median_rr_diaph');
    slow_measures.minimum_respiratory_rate_lungs_bpm = ...
        label_metric(label_evidence, 'slow', 'minimum_rr_lungs');
    slow_measures.minimum_respiratory_rate_diaph_bpm = ...
        label_metric(label_evidence, 'slow', 'minimum_rr_diaph');
    patterns.slow_breathing = respiratory_pattern( ...
        'Slow breathing', slow.available, slow_measures, {});

    rapid_measures = event_measures(rapid);
    rapid_measures.median_respiratory_rate_lungs_bpm = ...
        label_metric(label_evidence, 'rapid', 'median_rr_lungs');
    rapid_measures.median_respiratory_rate_diaph_bpm = ...
        label_metric(label_evidence, 'rapid', 'median_rr_diaph');
    rapid_measures.maximum_respiratory_rate_lungs_bpm = ...
        label_metric(label_evidence, 'rapid', 'maximum_rr_lungs');
    rapid_measures.maximum_respiratory_rate_diaph_bpm = ...
        label_metric(label_evidence, 'rapid', 'maximum_rr_diaph');
    patterns.rapid_breathing = respiratory_pattern( ...
        'Rapid breathing', rapid.available, rapid_measures, {});

    irregular_measures = event_measures(irregular);
    irregular_measures = add_label_metrics(irregular_measures, label_evidence, ...
        'irregular', {'median_cov_lungs', 'median_cov_diaph', ...
        'median_robust_cov_lungs', 'median_robust_cov_diaph'});
    patterns.irregular_breathing = respiratory_pattern( ...
        'Irregular breathing', irregular.available, irregular_measures, ...
        {'uses_the_existing_CoV_and_robust_CoV_definition'});

    sigh_measures = struct( ...
        'sigh_count', scalar_metric(label_burden, 'sigh_count'), ...
        'sighs_per_15_min', scalar_metric(label_burden, 'sighs_per_15_min'), ...
        'max_sighs_in_any_15_min_window', ...
            scalar_metric(label_burden, 'max_sighs_in_any_15_min_window'), ...
        'median_inter_sigh_interval_sec', ...
            scalar_metric(label_burden, 'median_inter_sigh_interval_sec'), ...
        'median_sigh_amplitude_ratio_lungs', ...
            label_metric(label_evidence, 'sigh', 'median_amplitude_ratio_lungs'), ...
        'median_sigh_amplitude_ratio_diaph', ...
            label_metric(label_evidence, 'sigh', 'median_amplitude_ratio_diaph'), ...
        'maximum_sigh_amplitude_ratio_lungs', ...
            label_metric(label_evidence, 'sigh', 'maximum_amplitude_ratio_lungs'), ...
        'maximum_sigh_amplitude_ratio_diaph', ...
            label_metric(label_evidence, 'sigh', 'maximum_amplitude_ratio_diaph'));
    patterns.sighing = respiratory_pattern( ...
        'Sighing', sigh.available, sigh_measures, ...
        {'amplitude_ratios_include_only_detected_evaluable_sigh_breaths'});

    desat_measures = event_measures(desat);
    desat_measures.minimum_spo2_percent = ...
        label_metric(label_evidence, 'desat', 'minimum_spo2_percent');
    desat_measures.maximum_drop_from_reference_percent = ...
        label_metric(label_evidence, 'desat', ...
            'maximum_drop_from_reference_percent');
    desat_measures = add_label_metrics(desat_measures, label_evidence, ...
        'desat', {'minimum_event_nadir_spo2_percent', ...
        'median_event_session_drop_pp', 'median_event_local_drop_pp'});
    patterns.desaturation = respiratory_pattern( ...
        'Desaturation', desat.available, desat_measures, ...
        {'pulse_oximetry_pattern_evidence_not_an_etiologic_diagnosis'});

    evidence.prespecified_db = add_provenance(prespecified, source_provenance);
    evidence.respiratory_patterns = add_provenance(patterns, source_provenance);

    % Backward-compatible aliases for the original five top-level readers.
    evidence.hyperventilation_syndrome = ...
        evidence.prespecified_db.hyperventilation_like;
    evidence.periodic_deep_sighing = ...
        evidence.prespecified_db.periodic_deep_sighing;
    evidence.thoracic_dominant_breathing = ...
        evidence.prespecified_db.thoracic_dominant_breathing;
    evidence.forced_abdominal_expiration = ...
        evidence.prespecified_db.forced_abdominal_expiration;
    evidence.thoracoabdominal_asynchrony = ...
        evidence.prespecified_db.thoracoabdominal_asynchrony;
end

function entry = burden_entry(burden, name)
% BURDEN_ENTRY Read one label burden with stable NaN fallbacks.

    entry = struct('available', false, 'duration_sec', NaN, 'fraction', NaN, ...
        'event_count', NaN, 'assessable_duration_sec', NaN, ...
        'median_event_duration_sec', NaN, 'max_event_duration_sec', NaN);
    if isstruct(burden) && isfield(burden, 'by_label') && ...
            isfield(burden.by_label, name)
        source = burden.by_label.(name);
        fields = fieldnames(entry);
        for i = 1:numel(fields)
            if isfield(source, fields{i})
                entry.(fields{i}) = source.(fields{i});
            end
        end
    end
end

function out = overlap_entry(overlaps, name)
% OVERLAP_ENTRY Read one compact overlap summary.

    out = struct();
    if isstruct(overlaps) && isfield(overlaps, name)
        out = overlaps.(name);
    end
end

function measures = event_measures(entry)
% EVENT_MEASURES Select the common continuous event metrics.

    measures = struct( ...
        'fraction', entry.fraction, ...
        'event_count', entry.event_count, ...
        'median_event_duration_sec', entry.median_event_duration_sec, ...
        'max_event_duration_sec', entry.max_event_duration_sec);
end

function value = scalar_metric(source, field)
% SCALAR_METRIC Return a top-level saved metric or NaN.

    value = metric(source, field, NaN);
end

function value = label_metric(summary, label, field, default_value)
% LABEL_METRIC Return one compact label-evidence field.

    if nargin < 4, default_value = NaN; end
    value = default_value;
    if isstruct(summary) && isfield(summary, label)
        value = metric(summary.(label), field, default_value);
    end
end

function value = metric(source, field, default_value)
% METRIC Return a present nonempty field or its fallback.

    if nargin < 3, default_value = NaN; end
    value = default_value;
    if isstruct(source) && isfield(source, field) && ~isempty(source.(field))
        value = source.(field);
    end
end

function measures = add_label_metrics(measures, summary, label, fields)
% ADD_LABEL_METRICS Copy named compact fields without copying diagnostic traces.

    for i = 1:numel(fields)
        measures.(fields{i}) = label_metric(summary, label, fields{i});
    end
end

function group = add_provenance(group, source_provenance)
% ADD_PROVENANCE Attach annotation-layer provenance to every phenotype.

    fields = fieldnames(group);
    for i = 1:numel(fields)
        group.(fields{i}).source_provenance = source_provenance;
        group.(fields{i}).external_clinical_data_integrated = false;
    end
end

function out = respiratory_pattern(name, available, measures, limitations)
% RESPIRATORY_PATTERN Package one non-diagnostic signal-derived profile.

    out = phenotype(name, true, available, measures, {}, ...
        [{'continuous_signal_derived_pattern_not_a_diagnosis'}, limitations]);
end

function out = phenotype(name, assessable, available, measures, required, limitations)
% PHENOTYPE Package one descriptive phenotype's evidence and limitations.

    out = struct( ...
        'name', name, ...
        'assessable_from_current_signals', logical(assessable), ...
        'evidence_available', logical(available), ...
        'signal_derived_measures', measures, ...
        'required_external_clinical_data', {required}, ...
        'limitations', {limitations});
end

function external = empty_external_clinical_data()
% EMPTY_EXTERNAL_CLINICAL_DATA Declare supported but unintegrated inputs.

    missing_entry = struct('available', false, 'value', [], ...
        'source', 'not_integrated');
    external = struct( ...
        'status', 'not_integrated', ...
        'Nijmegen_Questionnaire', missing_entry, ...
        'ETCO2_or_capnography', missing_entry, ...
        'CPET_or_ergospirometry', missing_entry, ...
        'clinical_observations', missing_entry, ...
        'Beck_Anxiety_Inventory', missing_entry);
end
