function ev = empty_events()
% EMPTY_EVENTS Create an empty events value.
%
% Syntax:
%   ev = empty_events()
%
% Outputs:
%   ev - Event structure array.

    ev = struct( ...
        'type', {}, ...
        'start_idx', {}, ...
        'end_idx', {}, ...
        'start_t', {}, ...
        'end_t', {}, ...
        'duration', {} );
end