function candidates = empty_candidate_events()
% EMPTY_CANDIDATE_EVENTS Return the canonical compact candidate-event array.
% Candidate structs deliberately omit label/detector provenance because the
% containing candidate_events.<label> field supplies that identity.

    candidates = struct( ...
        'start_idx', {}, ...
        'end_idx', {}, ...
        'start_t', {}, ...
        'end_t', {}, ...
        'duration', {}, ...
        'belt', {}, ...
        'accepted', {}, ...
        'rejection_reason', {}, ...
        'uncertainty_sec', {});
end
