function schema = get_phenotype_feature_schema()
% GET_PHENOTYPE_FEATURE_SCHEMA Define the fixed Level-2B phenotype features.
% This is the sole authority for feature names, order, display metadata, roles,
% units, and human-readable source descriptions used by recording, HDF5, and
% cohort outputs. Values are raw recording-level measures; no scaling,
% imputation, or data-driven feature selection is performed here.

    schema = struct();
    schema.version = 'magma_compact_phenotype_feature_schema_v1';
    schema.n_features = 21;
    schema.feature_names = { ...
        'db_hyperventilation_rapid_fraction', ...
        'db_hyperventilation_deep_fraction', ...
        'db_hyperventilation_rapid_deep_overlap_fraction', ...
        'db_hyperventilation_median_rr_bpm', ...
        'db_hyperventilation_median_relative_excursion', ...
        'db_periodic_deep_sighing_sighs_per_15_min', ...
        'db_periodic_deep_sighing_max_sighs_15_min', ...
        'db_periodic_deep_sighing_irregular_fraction', ...
        'db_periodic_deep_sighing_sigh_irregular_overlap_fraction', ...
        'db_periodic_deep_sighing_median_ibi_cov', ...
        'db_thoracic_dominant_fraction', ...
        'db_thoracic_dominant_median_ta_ratio', ...
        'db_thoracic_dominant_median_event_duration_sec', ...
        'db_asynchrony_fraction', ...
        'db_asynchrony_median_abs_phase_deg', ...
        'db_asynchrony_median_event_duration_sec', ...
        'pattern_apnea_fraction', ...
        'pattern_periodic_fraction', ...
        'pattern_shallow_fraction', ...
        'pattern_slow_fraction', ...
        'pattern_desaturation_fraction'};
    schema.display_name = { ...
        'Rapid-breathing burden', ...
        'Deep-breathing burden', ...
        'Rapid-deep joint-assessable overlap', ...
        'Median respiratory rate', ...
        'Median relative breath excursion', ...
        'Sigh frequency', ...
        'Maximum sigh count in an assessable 15-minute window', ...
        'Irregular-breathing burden', ...
        'Sigh events during irregular breathing', ...
        'Median inter-breath-interval coefficient of variation', ...
        'Thoracic-dominant burden', ...
        'Median thoracic-to-abdominal excursion ratio', ...
        'Median thoracic-dominant event duration', ...
        'Thoraco-abdominal asynchrony burden', ...
        'Median absolute thoraco-abdominal phase offset', ...
        'Median thoraco-abdominal asynchrony event duration', ...
        'Apneic-breathing burden', ...
        'Periodic-breathing burden', ...
        'Shallow-breathing burden', ...
        'Slow-breathing burden', ...
        'Desaturation burden'};
    schema.phenotype_group = { ...
        'hyperventilation_like', 'hyperventilation_like', ...
        'hyperventilation_like', 'hyperventilation_like', ...
        'hyperventilation_like', ...
        'periodic_deep_sighing', 'periodic_deep_sighing', ...
        'periodic_deep_sighing', 'periodic_deep_sighing', ...
        'periodic_deep_sighing', ...
        'thoracic_dominant_breathing', 'thoracic_dominant_breathing', ...
        'thoracic_dominant_breathing', ...
        'thoracoabdominal_asynchrony', 'thoracoabdominal_asynchrony', ...
        'thoracoabdominal_asynchrony', ...
        'apneic_breathing', 'periodic_breathing', 'shallow_breathing', ...
        'slow_breathing', 'desaturation'};
    schema.feature_role = [repmat({'prespecified_db'}, 1, 16), ...
        repmat({'additional_pattern'}, 1, 5)];
    schema.units = { ...
        'fraction', 'fraction', 'fraction', 'breaths_per_min', 'ratio', ...
        'events_per_15_min', 'events_per_15_min', 'fraction', 'fraction', ...
        'dimensionless', 'fraction', 'ratio', 'seconds', 'fraction', ...
        'degrees', 'seconds', 'fraction', 'fraction', 'fraction', ...
        'fraction', 'fraction'};
    schema.source_description = { ...
        'Rapid-label duration divided by rapid-assessable duration.', ...
        'Deep-label duration divided by deep-assessable duration.', ...
        'Rapid-and-deep overlap duration divided by jointly assessable duration.', ...
        'Median of finite per-belt recording-scope rapid-detector rate medians.', ...
        'Median of finite per-belt recording-scope session-normalized excursion medians.', ...
        'Canonical sigh count normalized to 15 minutes of sigh-assessable time.', ...
        'Maximum canonical sigh count in a continuously assessable 15-minute interval.', ...
        'Irregular-label duration divided by irregular-assessable duration.', ...
        'Fraction of assessable canonical sigh events whose midpoint is irregular-positive.', ...
        'Median of finite per-belt recording-scope ordinary IBI CoV medians.', ...
        'Thoracic-dominant duration divided by thoracic-assessable duration.', ...
        'Recording-scope median normalized thoracic-to-abdominal excursion ratio.', ...
        'Median canonical thoracic-dominant event duration; zero when assessable with no events.', ...
        'Asynchrony duration divided by asynchrony-assessable duration.', ...
        'Recording-scope median absolute phase offset over reliable phase evidence.', ...
        'Median canonical asynchrony event duration; zero when assessable with no events.', ...
        'Apnea-label duration divided by apnea-assessable duration.', ...
        'Periodic-breathing duration divided by periodic-assessable duration.', ...
        'Shallow-breathing duration divided by shallow-assessable duration.', ...
        'Slow-breathing duration divided by slow-assessable duration.', ...
        'Desaturation duration divided by desaturation-assessable duration.'};

    metadata_fields = {'feature_names', 'display_name', 'phenotype_group', ...
        'feature_role', 'units', 'source_description'};
    for i = 1:numel(metadata_fields)
        if numel(schema.(metadata_fields{i})) ~= schema.n_features
            error('MAGMA:PhenotypeFeatures:InvalidSchema', ...
                '%s must contain exactly %d entries.', ...
                metadata_fields{i}, schema.n_features);
        end
        schema.(metadata_fields{i}) = reshape( ...
            cellstr(string(schema.(metadata_fields{i}))), 1, []);
    end
    if numel(unique(schema.feature_names)) ~= schema.n_features
        error('MAGMA:PhenotypeFeatures:InvalidSchema', ...
            'Compact phenotype feature names must be unique.');
    end
end
