function info = make_label_boundary_info( ...
    label, detector, method, candidate_events, localized_events, ...
    uncertainty_sec, evidence_source, evidence_endpoint_mask, ...
    candidate_support_mask, localized_state_mask, final_state_mask)
% MAKE_LABEL_BOUNDARY_INFO Package detector timing evidence and provenance.
% Inputs identify the label/detector/method/source, candidate and localized
% event arrays, uncertainty in seconds, and grid-level endpoint, candidate,
% localized, and final masks. info fields mirror those values and add
% rejected_localized_mask plus per-event records. Each record stores label,
% detector, method, candidate/localized times, localized/final-duration status,
% rejection reason, uncertainty_sec, and evidence_source.

    if nargin < 8 || isempty(evidence_endpoint_mask), evidence_endpoint_mask = []; end
    if nargin < 9 || isempty(candidate_support_mask), candidate_support_mask = []; end
    if nargin < 10 || isempty(localized_state_mask), localized_state_mask = []; end
    if nargin < 11 || isempty(final_state_mask), final_state_mask = localized_state_mask; end

    info = struct( ...
        'label', char(string(label)), ...
        'detector', char(string(detector)), ...
        'boundary_method', char(string(method)), ...
        'boundary_uncertainty_sec', uncertainty_sec, ...
        'evidence_source', char(string(evidence_source)), ...
        'evidence_endpoint_mask', logical(evidence_endpoint_mask), ...
        'candidate_support_mask', logical(candidate_support_mask), ...
        'localized_state_mask', logical(localized_state_mask), ...
        'final_state_mask', logical(final_state_mask), ...
        'rejected_localized_mask', logical(localized_state_mask) & ...
            ~logical(final_state_mask), ...
        'events', boundary_records(label, detector, method, candidate_events, ...
            localized_events, uncertainty_sec, evidence_source));
end

function records = boundary_records(label, detector, method, candidates, localized, uncertainty, source)
% BOUNDARY_RECORDS Align candidate/localized events into provenance records.
% Text inputs are copied to each record; uncertainty may be scalar or per-event.
% Missing event counterparts remain NaN, while localized events initially pass.

    template = struct( ...
        'label', char(string(label)), ...
        'detector', char(string(detector)), ...
        'boundary_method', char(string(method)), ...
        'candidate_start_t', NaN, ...
        'candidate_end_t', NaN, ...
        'localized_start_t', NaN, ...
        'localized_end_t', NaN, ...
        'localized_duration_sec', NaN, ...
        'final_min_duration_sec', NaN, ...
        'passes_final_min_duration', false, ...
        'rejection_reason', '', ...
        'uncertainty_sec', NaN, ...
        'evidence_source', char(string(source)));
    records = template([]);
    n = max(numel(candidates), numel(localized));
    if n == 0
        return;
    end
    records = repmat(template, n, 1);
    for i = 1:n
        c = event_at(candidates, i);
        l = event_at(localized, i);
        if ~isempty(c)
            records(i).candidate_start_t = c.start_t;
            records(i).candidate_end_t = c.end_t;
        end
        if ~isempty(l)
            records(i).localized_start_t = l.start_t;
            records(i).localized_end_t = l.end_t;
            records(i).localized_duration_sec = l.duration;
            records(i).passes_final_min_duration = true;
        end
        records(i).uncertainty_sec = scalar_or_index(uncertainty, i);
    end
end

function event = event_at(events, i)
% EVENT_AT Return event i, repeating the final event when i exceeds the array.

    event = [];
    if ~isempty(events)
        event = events(min(i, numel(events)));
    end
end

function value = scalar_or_index(values, i)
% SCALAR_OR_INDEX Expand scalar metadata or read a clamped vector element.
% Empty input maps to NaN.

    if isempty(values)
        value = NaN;
    elseif isscalar(values)
        value = values;
    else
        value = values(min(i, numel(values)));
    end
end
