function label_defs = manual_label_definitions()
% manual_label_definitions
% Labels handled by the final manual event editor.

    label_defs = struct( ...
        'field',        {'shallowB', 'deepB', 'irregB', 'slowB', 'rapidB', 'asyncB', 'desat', 'apnea', 'CSR'}, ...
        'type',         {'shallowB', 'deepB', 'irregB', 'slowB', 'rapidB', 'asyncB', 'desat', 'apnea', 'CSR'}, ...
        'name',         {'Shallow breathing', 'Deep breathing', 'Irregular breathing', 'Slow breathing', 'Rapid breathing', ...
                         'Respiratory asynchrony', 'Desaturation', 'Apnea', 'Periodic breathing'}, ...
        'plot_name',    {'shallow_breathing', 'deep_breathing', 'irregular_breathing', 'slow_breathing', 'rapid_breathing', ...
                         'respiratory_asynchrony', 'desaturation', 'apnea', 'periodic_breathing'}, ...
        'config_field', {'ShB', 'DeB', 'IrB', 'SlB', 'RaB', 'ReA', 'Des', 'Apn', 'CSR'} );
end
