function label_defs = manual_label_definitions()
% manual_label_definitions
% Labels handled by the final manual event editor.

    label_defs = struct( ...
        'field',        {'shallow', 'deep', 'slow', 'rapid', 'irregular', 'apnea', 'csr', 'thoracic', 'async', 'desat'}, ...
        'type',         {'shallow', 'deep', 'slow', 'rapid', 'irregular', 'apnea', 'csr', 'thoracic', 'async', 'desat'}, ...
        'name',         {'Shallow breathing', 'Deep breathing', 'Slow breathing', 'Rapid breathing', 'Irregular breathing', 'Apnea', ...
                         'Periodic breathing', 'Thoracic-dominant breathing', 'Respiratory asynchrony', 'Desaturation'}, ...
        'plot_name',    {'shallow_breathing', 'deep_breathing', 'slow_breathing', 'rapid_breathing', 'irregular_breathing', 'apnea', ...
                         'periodic_breathing', 'thoracic_dominant_breathing', 'respiratory_asynchrony', 'desaturation'}, ...
        'config_field', {'ShB', 'DeB', 'SlB', 'RaB', 'IrB', 'Apn', 'CSR', 'TDB', 'ReA', 'Des'} );
end
