function label_defs = manual_label_definitions()
% MANUAL_LABEL_DEFINITIONS Define editable labels and their UI/config mappings.
% The struct array excludes separately reviewed sighs. Each entry contains field,
% canonical type, display name, plot_name, and config_field.

    label_defs = struct( ...
        'field',        {'shallow', 'deep', 'slow', 'rapid', 'irregular', 'apnea', 'csr', 'thoracic', 'async', 'desat'}, ...
        'type',         {'shallow', 'deep', 'slow', 'rapid', 'irregular', 'apnea', 'csr', 'thoracic', 'async', 'desat'}, ...
        'name',         {'Shallow breathing', 'Deep breathing', 'Slow breathing', 'Rapid breathing', 'Irregular breathing', 'Apnea', ...
                         'Periodic breathing', 'Thoracic-dominant breathing', 'Respiratory asynchrony', 'Desaturation'}, ...
        'plot_name',    {'shallow_breathing', 'deep_breathing', 'slow_breathing', 'rapid_breathing', 'irregular_breathing', 'apnea', ...
                         'periodic_breathing', 'thoracic_dominant_breathing', 'respiratory_asynchrony', 'desaturation'}, ...
        'config_field', {'shallow', 'deep', 'slow', 'rapid', 'irregular', 'apnea', 'csr', 'thoracic', 'async', 'desat'} );
end
