function detections = run_selected_label_detectors( ...
    data, resp_features, resp_cycles, resp_ref, session_reference, ...
    config, selected_labels, existing_results)
% RUN_SELECTED_LABEL_DETECTORS Execute the requested canonical detectors.
% Empty selected_labels executes every detector. When existing_results is
% supplied, unselected events, candidates, diagnostics, and SpO2 reference
% are carried forward unchanged for the later merge step.

    if nargin < 8 || isempty(existing_results)
        existing_results = struct();
    end
    labels = get_labels('short');
    detections = initialize_detections( ...
        existing_results, labels, resp_features, data, session_reference, ...
        config, selected_labels);

    if should_run_label('shallow', selected_labels)
        log_message(config, 2, 'Detecting shallow breathing...');
        [detections.events.shallow, detections.candidate_events.shallow] = ...
            detect_shallow_breathing(data, resp_features, config);
    end
    if should_run_label('deep', selected_labels)
        log_message(config, 2, 'Detecting deep breathing...');
        [detections.events.deep, detections.candidate_events.deep] = ...
            detect_deep_breathing(data, resp_features, config);
    end
    if should_run_label('slow', selected_labels)
        log_message(config, 2, 'Detecting slow breathing...');
        [detections.events.slow, detections.candidate_events.slow] = ...
            detect_slow_breathing(data, resp_features, config);
    end
    if should_run_label('rapid', selected_labels)
        log_message(config, 2, 'Detecting rapid breathing...');
        [detections.events.rapid, detections.candidate_events.rapid] = ...
            detect_rapid_breathing(data, resp_features, config);
    end
    if should_run_label('irregular', selected_labels)
        log_message(config, 2, 'Detecting irregular breathing...');
        [detections.events.irregular, detections.candidate_events.irregular] = ...
            detect_irregular_breathing(data, resp_features, config);
    end
    if should_run_label('apnea', selected_labels)
        log_message(config, 2, 'Detecting apnea...');
        [detections.events.apnea, detections.diagnostics.apnea, ...
            detections.candidate_events.apnea] = ...
            detect_apnea(data, resp_features, resp_ref, config);
    end
    if should_run_label('sigh', selected_labels)
        log_message(config, 2, 'Detecting sighs...');
        [detections.events.sigh, detections.diagnostics.sigh] = ...
            detect_sigh(data, resp_features, resp_cycles, config);
        detections.candidate_events.sigh = empty_candidate_events();
    end
    if should_run_label('periodic', selected_labels)
        log_message(config, 2, 'Detecting periodic breathing...');
        [detections.events.periodic, detections.diagnostics.periodic, ...
            detections.candidate_events.periodic] = ...
            detect_periodic_breathing(data, resp_cycles, config);
    end
    if should_run_label('thoracic', selected_labels)
        log_message(config, 2, 'Detecting thoracic dominance...');
        [detections.events.thoracic, ...
            detections.candidate_events.thoracic] = ...
            detect_thoracic_dominant_breathing(data, resp_features, config);
    end
    if should_run_label('async', selected_labels)
        log_message(config, 2, 'Detecting respiratory asynchrony...');
        [detections.events.async, detections.diagnostics.async] = ...
            detect_respiratory_asynchrony( ...
                data, session_reference, resp_cycles, config);
        detections.candidate_events.async = empty_candidate_events();
    end
    if should_run_label('desat', selected_labels)
        log_message(config, 2, 'Detecting desaturation...');
        [detections.events.desat, detections.diagnostics.desat, ...
            detections.spo2_ref] = ...
            detect_desaturation(data, session_reference, config);
        detections.candidate_events.desat = empty_candidate_events();
    end
end

function detections = initialize_detections( ...
    existing, labels, resp_features, data, session_reference, config, ...
    selected_labels)
% INITIALIZE_DETECTIONS Build a complete canonical detector container.

    detections = struct();
    detections.events = event_sets_from_existing(existing, labels);
    detections.candidate_events = candidate_sets_from_existing(existing, labels);
    detections.diagnostics = empty_diagnostics(resp_features);
    if isfield(existing, 'detector_diagnostics') && ...
            isstruct(existing.detector_diagnostics)
        names = fieldnames(existing.detector_diagnostics);
        for i = 1:numel(names)
            detections.diagnostics.(names{i}) = ...
                existing.detector_diagnostics.(names{i});
        end
    end
    if isfield(existing, 'spo2_ref') && isstruct(existing.spo2_ref)
        detections.spo2_ref = existing.spo2_ref;
    elseif should_run_label('desat', selected_labels)
        % The desaturation detector replaces this without a duplicate
        % reference calculation.
        detections.spo2_ref = struct();
    else
        % Keep the normal reference schema even when desaturation itself was
        % not requested in a new partial analysis.
        detections.spo2_ref = compute_spo2_reference( ...
            data, session_reference, config);
    end
end

function sets = event_sets_from_existing(existing, labels)
% EVENT_SETS_FROM_EXISTING Split the saved canonical automatic event array.

    sets = struct();
    events = empty_events();
    if isfield(existing, 'events_automatic') && ...
            isstruct(existing.events_automatic)
        events = existing.events_automatic;
    end
    for i = 1:numel(labels)
        if isempty(events)
            sets.(labels{i}) = empty_events();
        else
            sets.(labels{i}) = events(strcmp({events.type}, labels{i}));
        end
    end
end

function sets = candidate_sets_from_existing(existing, labels)
% CANDIDATE_SETS_FROM_EXISTING Return one compact array per canonical label.

    sets = struct();
    for i = 1:numel(labels)
        label = labels{i};
        if isfield(existing, 'candidate_events') && ...
                isstruct(existing.candidate_events) && ...
                isfield(existing.candidate_events, label)
            sets.(label) = existing.candidate_events.(label);
        else
            sets.(label) = empty_candidate_events();
        end
    end
end

function diagnostics = empty_diagnostics(resp_features)
% EMPTY_DIAGNOSTICS Supply non-assessable placeholders for skipped detectors.

    n_grid = numel(resp_features.time_sec);
    empty_raw = struct( ...
        'excursion_ratio', nan(n_grid, 1), ...
        'evaluable_endpoint_mask', false(n_grid, 1));
    diagnostics = struct();
    diagnostics.async = struct( ...
        'valid_analysis', false, ...
        'reference_available', false, ...
        'reference_quality', struct(), ...
        'skip_code', NaN, ...
        'error_message', 'not_computed', ...
        'references', struct(), ...
        'thresholds', struct(), ...
        'phase_coherence_high', [], ...
        'phase_coherence_mid', [], ...
        'phase_coherence_low', [], ...
        'deviation_bin_count', []);
    diagnostics.desat = struct( ...
        'signal_available', false, ...
        'detection_available', false, ...
        'absolute_available', false, ...
        'relative_available', false, ...
        'detection_mode', 'not_computed', ...
        'event_metrics_automatic', struct([]));
    diagnostics.apnea = struct( ...
        'available', false, ...
        'amplitude_path_available', false, ...
        'raw_excursion_path_available', false, ...
        'amplitude_support_belts', '', ...
        'raw_excursion_support_belts', '', ...
        'amplitude_state_mask', false(n_grid, 1), ...
        'raw_fallback_state_mask', false(n_grid, 1), ...
        'combined_endpoint_mask', false(n_grid, 1), ...
        'raw_excursion', struct('lungs', empty_raw, 'diaph', empty_raw));
    empty_sigh_belt = struct( ...
        'available', false, ...
        'decision_threshold', NaN, ...
        'sigh_ratio', [], ...
        'evaluable_mask', false(0, 1));
    diagnostics.sigh = struct( ...
        'available', false, ...
        'lungs', empty_sigh_belt, ...
        'diaph', empty_sigh_belt);
    empty_eami_belt = struct('available', false, 'index', []);
    empty_guyot_belt = struct( ...
        'available', false, 'h', [], 'fm_hz', []);
    diagnostics.periodic = struct( ...
        'available', false, ...
        'primary_method', 'not_computed', ...
        'eami', struct( ...
            'available', false, ...
            'lungs', empty_eami_belt, ...
            'diaph', empty_eami_belt, ...
            'event_count', 0, ...
            'event_duration_sec', 0), ...
        'guyot', struct( ...
            'available', false, ...
            'lungs', empty_guyot_belt, ...
            'diaph', empty_guyot_belt, ...
            'event_count', 0, ...
            'event_duration_sec', 0));
end
