function labels = get_labels(format)
% GET_LABELS Return canonical label metadata.
%
% Syntax:
%   labels = get_labels()
%   labels = get_labels(format)
%
% Inputs:
%   format - Optional output format:
%            'short' returns canonical short names,
%            'long' returns canonical long names,
%            'idx' returns canonical numeric indices.
%            If omitted, the full label metadata structure is returned.
%
% Outputs:
%   labels - Full label metadata structure or the requested label
%            representation.

    labels_long = { ...
        'ShallowBreathing', ...
        'DeepBreathing', ...
        'SlowBreathing', ...
        'RapidBreathing', ...
        'IrregularBreathing', ...
        'Apnea', ...
        'Sigh', ...
        'PeriodicBreathingCheyneStokesLike', ...
        'ThoracicDominantBreathing', ...
        'RespiratoryAsynchrony', ...
        'Desaturation'};

    labels_short = { ...
        'shallow', ...
        'deep', ...
        'slow', ...
        'rapid', ...
        'irregular', ...
        'apnea', ...
        'sigh', ...
        'csr', ...
        'thoracic', ...
        'async', ...
        'desat'};

    labels_idx = 1:numel(labels_short);

    labels_full = struct( ...
        'idx',   num2cell(labels_idx), ...
        'long',  labels_long, ...
        'short', labels_short);

    if nargin < 1 || isempty(format)
        labels = labels_full;
        return;
    end

    format = lower(char(string(format)));

    switch format
        case 'short'
            labels = labels_short;

        case 'long'
            labels = labels_long;

        case 'idx'
            labels = labels_idx;

        otherwise
            error('MAGMA:GetLabels:InvalidFormat', ...
                'Unknown label format "%s". Use short, long, or idx.', format);
    end
end
