
%---- SETTINGS ----
config = get_config();

%---- MEASUREMENT AND SUBJECT LOOPS
for isub = 1:length(config.subjects)
    for imeasure = 1:length(config.measurements)

        config.subject = config.subjects(isub);
        config.measure = config.measurements(imeasure);
        
        % LOAD DATA
        [data_raw, config, do_analysis] = load_raw_data(config);
        if ~do_analysis
            continue;
        end
        
        % PREPROCESS DATA
        [data, config] = preprocess_data(data_raw, config);

        % RESPIRATORY CYCLES
        resp_cycles = load_or_extract_respiratory_cycles(data, config);

        % MODALITY-SPECIFIC REFERENCES FROM THE COMMON INTERVAL
        session_reference = get_session_reference_interval(size(data, 1), config);
        resp_ref = compute_respiratory_reference(resp_cycles, session_reference, config);
        spo2_ref = compute_spo2_reference(data, session_reference, config);
        plot_session_reference(data, resp_cycles, resp_ref, spo2_ref, session_reference, config);

        % RESPIRATORY FEATURES (derived; no peak redetection)
        resp_features = compute_respiratory_features(data, resp_cycles, resp_ref, config);

        % LABEL DETECTIONS        
        [events_shallow, boundary_shallow] = detect_shallow_breathing(data, resp_features, config);
        [events_deep, boundary_deep] = detect_deep_breathing(data, resp_features, config);
        [events_thoracic, boundary_thoracic] = detect_thoracic_dominant_breathing(data, resp_features, config);
        [events_irregular, boundary_irregular] = detect_irregular_breathing(data, resp_features, config);
        [events_slow, boundary_slow] = detect_slow_breathing(data, resp_features, config);
        [events_rapid, boundary_rapid] = detect_rapid_breathing(data, resp_features, config);
        [events_async, diagnostics_async] = detect_respiratory_asynchrony(data, session_reference, resp_cycles, config);
        [events_desat, diagnostics_desat] = detect_desaturation(data, spo2_ref, session_reference, config);
        [events_apnea, diagnostics_apnea, boundary_apnea] = detect_apnea(data, resp_features, session_reference, config);
        [~, diagnostics_sigh, sigh_review] = detect_sigh(data, resp_features, resp_cycles, spo2_ref, session_reference, diagnostics_desat, config);
        [events_csr, diagnostics_csr] = detect_periodic_breathing(data, resp_cycles, config);
 
        % Freeze automatic annotations before any interval editing.
        % Sigh is separate because it has its own breath-level GUI, whose
        % automatic candidates are retained in sigh_review.automatic_events.
        automatic_event_sets = struct( ...
            'shallow', events_shallow, ...
            'deep', events_deep, ...
            'thoracic', events_thoracic, ...
            'irregular', events_irregular, ...
            'slow', events_slow, ...
            'rapid', events_rapid, ...
            'async', events_async, ...
            'desat', events_desat, ...
            'apnea', events_apnea, ...
            'csr', events_csr);
        N = size(data,1);
        [reviewed_event_sets, manual_label_edit] = manual_edit_label_events(data, config, automatic_event_sets);
        annotations = assemble_annotation_layers(automatic_event_sets, reviewed_event_sets, manual_label_edit, sigh_review, N, config);
        events_automatic = annotations.events_automatic;
        mask_automatic = annotations.mask_automatic;
        events_reviewed = annotations.events_reviewed;
        mask_reviewed = annotations.mask_reviewed;
        gold_review_mask = annotations.gold_review_mask;
        label_names = annotations.label_names;

        [label_available, label_availability_reason] = ...
            compute_label_availability(label_names, resp_features, diagnostics_desat, ...
                diagnostics_async, diagnostics_apnea, diagnostics_sigh, diagnostics_csr);
        [label_assessable_mask, label_assessability_info] = ...
            compute_label_assessable_mask(N, label_names, label_available, ...
                diagnostics_desat, diagnostics_async, config);
        diagnostic_signals = compute_label_diagnostic_signals( ...
            resp_features, spo2_ref, diagnostics_desat, config, diagnostics_async, ...
            diagnostics_apnea, diagnostics_sigh, diagnostics_csr);
        detector_diagnostics = struct( ...
            'respiratory_asynchrony', diagnostics_async, ...
            'desaturation', diagnostics_desat, ...
            'apnea', diagnostics_apnea, ...
            'sigh', diagnostics_sigh, ...
            'periodic_breathing', diagnostics_csr);
        label_burden_automatic = compute_recording_label_burden( ...
            mask_automatic, label_names, label_available, events_automatic, config.fs, ...
            label_assessable_mask);
        label_overlap_summary_automatic = compute_label_overlap_summary( ...
            mask_automatic, label_names, label_available, config.fs, label_assessable_mask);
        label_evidence_summary_automatic = build_label_evidence_summary( ...
            label_names, label_available, label_availability_reason, ...
            resp_features, diagnostic_signals, detector_diagnostics, label_burden_automatic);

        [reviewed_assessable_mask, reviewed_available, reviewed_reasons] = ...
            compute_reviewed_label_availability( ...
                label_available, label_availability_reason, ...
                label_assessable_mask, gold_review_mask);
        label_burden_reviewed = compute_recording_label_burden( ...
            mask_reviewed, label_names, reviewed_available, events_reviewed, ...
            config.fs, reviewed_assessable_mask);
        label_overlap_summary_reviewed = compute_label_overlap_summary( ...
            mask_reviewed, label_names, reviewed_available, config.fs, ...
            reviewed_assessable_mask);
        label_evidence_summary_reviewed = build_label_evidence_summary( ...
            label_names, reviewed_available, reviewed_reasons, resp_features, ...
            diagnostic_signals, detector_diagnostics, label_burden_reviewed);
        db_phenotype_evidence = build_db_phenotype_evidence_bundle( ...
            label_burden_automatic, label_overlap_summary_automatic, ...
            label_evidence_summary_automatic, label_burden_reviewed, ...
            label_overlap_summary_reviewed, label_evidence_summary_reviewed);

        event_boundary_info = struct( ...
            'version', 'label_boundary_provenance_v1', ...
            'shallow', boundary_shallow, 'deep', boundary_deep, ...
            'slow', boundary_slow, 'rapid', boundary_rapid, ...
            'irregular', boundary_irregular, ...
            'apnea', boundary_apnea, ...
            'sigh', standard_boundary('sigh', 'detect_sigh', ...
                sigh_review.automatic_events, 'breath_midpoint_cell', 1/config.fs, ...
                'automatic_sigh_candidate_breath'), ...
            'csr', standard_boundary('csr', 'detect_periodic_breathing', ...
                events_csr, 'cycle_trough_to_trough', 1/config.fs, ...
                'breath_amplitude_envelope_cycles'), ...
            'thoracic', boundary_thoracic, ...
            'async', standard_boundary('async', 'detect_respiratory_asynchrony', ...
                events_async, 'specialized_local_phase_coherence', NaN, ...
                'time_localized_wavelet_phase_coherence'), ...
            'desat', standard_boundary('desat', 'detect_desaturation', ...
                events_desat, 'native_spo2_threshold_run', 1/config.fs, 'native_spo2_samples'));
        rewritten_manual_label_figures = rewrite_changed_manual_label_figures( ...
            data, spo2_ref, session_reference, resp_cycles, diagnostics_desat, ...
            diagnostic_signals, reviewed_event_sets, manual_label_edit, config);
        plot_label_mask(mask_automatic, label_names, config);
        
        % SAVE
        results = struct();
        results.subject = config.subject;
        results.measure = config.measure;
        results.annotation_schema_version = annotations.version;
        results.events_automatic = events_automatic;
        results.mask_automatic = mask_automatic;
        results.events_reviewed = events_reviewed;
        results.mask_reviewed = mask_reviewed;
        results.gold_review_mask = gold_review_mask;
        results.review_status = annotations.review_status;
        results.review_scope = annotations.review_scope;
        results.review_history = annotations.review_history;
        results.review_provenance = annotations.review_provenance;
        results.label_names = label_names;
        results.label_available = label_available;
        results.label_availability_reason = label_availability_reason;
        results.label_assessable_mask = label_assessable_mask;
        results.label_assessability_info = label_assessability_info;
        results.label_reviewed_available = reviewed_available;
        results.label_reviewed_availability_reason = reviewed_reasons;
        results.label_reviewed_assessable_mask = reviewed_assessable_mask;
        results.label_schema_version = config.label_schema_version;
        results.resp_cycles = resp_cycles;
        results.resp_ref = resp_ref;
        results.session_reference = session_reference;
        results.spo2_ref = spo2_ref;
        results.resp_features = resp_features;
        results.diagnostic_signals = diagnostic_signals;
        results.detector_diagnostics = detector_diagnostics;
        results.label_burden_automatic = label_burden_automatic;
        results.label_burden_reviewed = label_burden_reviewed;
        results.label_overlap_summary_automatic = label_overlap_summary_automatic;
        results.label_overlap_summary_reviewed = label_overlap_summary_reviewed;
        results.label_evidence_summary_automatic = label_evidence_summary_automatic;
        results.label_evidence_summary_reviewed = label_evidence_summary_reviewed;
        results.db_phenotype_evidence = db_phenotype_evidence;
        results.event_boundary_info = event_boundary_info;
        results.manual_label_edit = manual_label_edit;
        results.manual_sigh_review = sigh_review;
        results.rewritten_manual_label_figures = rewritten_manual_label_figures;
        results.input_config = config.input_config;
        results.config = config;
        results.export_schema_version = get_config_value( ...
            config, 'HDF5', 'export_schema_version', 'magma_ml_hdf5_v4');
        results.upstream_input_preprocessing = get_config_value( ...
            config, 'HDF5', 'upstream_input_preprocessing', ...
            'external / not fully documented');
        save(fullfile(config.sub_results_path, config.sub_results_filename), '-struct', 'results');
        if get_config_value(config, 'HDF5', 'enabled', true)
            hdf5_suffix = get_config_value(config, 'HDF5', ...
                'filename_suffix', '_labels.h5');
            hdf5_filename = fullfile(config.sub_results_path, ...
                sprintf('Sub%d_M%d%s', config.subject, config.measure, hdf5_suffix));
            export_results_hdf5(hdf5_filename, results, data_raw, data);
        end
        
        disp(['Successfully finished label detection for: Sub ' num2str(config.subject) ' | Measurement: ' num2str(config.measure) ])
    end
end

save([config.path_results_out, filesep, 'analysis_configuration.mat'], "config")
