function tests = test_compact_phenotype_features
% Deterministic recording-level phenotype summary semantics and scope tests.
    tests = functiontests(localfunctions);
end

function testSchemaHasExactlyFixedUniqueTwentyOneFeatures(testCase)
    schema = get_phenotype_feature_schema();
    expected = { ...
        'db_hyperventilation_rapid_fraction', ...
        'db_hyperventilation_deep_fraction', ...
        'db_hyperventilation_rapid_deep_overlap_fraction', ...
        'db_hyperventilation_median_rr_bpm', ...
        'db_hyperventilation_median_relative_excursion', ...
        'db_periodic_deep_sighing_sighs_per_15_min', ...
        'db_periodic_deep_sighing_max_sighs_15_min', ...
        'db_periodic_deep_sighing_irregular_fraction', ...
        'db_periodic_deep_sighing_sigh_irregular_overlap_fraction', ...
        'db_periodic_deep_sighing_median_ibi_cov', ...
        'db_thoracic_dominant_fraction', ...
        'db_thoracic_dominant_median_ta_ratio', ...
        'db_thoracic_dominant_median_event_duration_sec', ...
        'db_asynchrony_fraction', ...
        'db_asynchrony_median_abs_phase_deg', ...
        'db_asynchrony_median_event_duration_sec', ...
        'pattern_apnea_fraction', 'pattern_periodic_fraction', ...
        'pattern_shallow_fraction', 'pattern_slow_fraction', ...
        'pattern_desaturation_fraction'};
    verifyEqual(testCase, schema.n_features, 21);
    verifyEqual(testCase, schema.feature_names, expected);
    verifyEqual(testCase, numel(unique(schema.feature_names)), 21);
    verifyEqual(testCase, nnz(strcmp(schema.feature_role, 'prespecified_db')), 16);
    verifyEqual(testCase, nnz(strcmp(schema.feature_role, 'additional_pattern')), 5);
    verifyFalse(testCase, any(contains(schema.feature_names, 'forced_abdominal')));
end

function testAdditionalPatternsAreNotDuplicated(testCase)
    [burden, overlap, evidence] = compact_fixture(900, true(900, 11));
    output = build_db_phenotype_evidence(burden, overlap, evidence);
    verifyEqual(testCase, fieldnames(output.respiratory_patterns), { ...
        'apneic_breathing'; 'periodic_breathing'; 'shallow_breathing'; ...
        'slow_breathing'; 'desaturation'});
    verifyTrue(testCase, isfield(burden.by_label, 'deep'));
    verifyTrue(testCase, isfield(burden.by_label, 'rapid'));
    verifyTrue(testCase, isfield(burden.by_label, 'irregular'));
    verifyTrue(testCase, isfield(burden.by_label, 'sigh'));
    verifyFalse(testCase, isfield(output, 'hyperventilation_syndrome'));
    verifyEqual(testCase, ...
        output.prespecified_db.hyperventilation_like.signal_assessment_status, ...
        'partial');
end

function testRapidDeepUsesJointAssessableDenominator(testCase)
    names = get_labels('short');
    mask = false(10, 11);
    rapid = strcmp(names, 'rapid');
    deep = strcmp(names, 'deep');
    mask(1:4, rapid) = true;
    mask(3:5, deep) = true;
    assessable = true(10, 11);
    assessable(6:10, deep) = false;
    overlap = compute_label_overlap_summary( ...
        mask, names, true(1, 11), 1, assessable, empty_events());
    verifyEqual(testCase, overlap.rapid_deep.overlap_duration_sec, 2);
    verifyEqual(testCase, overlap.rapid_deep.joint_assessable_duration_sec, 5);
    verifyEqual(testCase, ...
        overlap.rapid_deep.overlap_fraction_of_joint_assessable, 0.4);
    verifyEqual(testCase, ...
        overlap.rapid_deep.fraction_of_a_overlapped_by_b, 0.5);
    verifyNotEqual(testCase, ...
        overlap.rapid_deep.overlap_fraction_of_joint_assessable, ...
        overlap.rapid_deep.fraction_of_a_overlapped_by_b);
end

function testSighIrregularOverlapIsEventFraction(testCase)
    names = get_labels('short');
    mask = false(10, 11);
    sigh = strcmp(names, 'sigh');
    irregular = strcmp(names, 'irregular');
    mask(:, sigh) = true;
    mask(2, irregular) = true;
    events = [event('sigh', 1, 3, 1), event('sigh', 7, 9, 1)];
    overlap = compute_label_overlap_summary( ...
        mask, names, true(1, 11), 1, true(10, 11), events);
    verifyEqual(testCase, ...
        overlap.sigh_irregular.assessable_a_event_count, 2);
    verifyEqual(testCase, ...
        overlap.sigh_irregular.fraction_of_a_events_with_b_at_midpoint, 0.5);
    verifyEqual(testCase, ...
        overlap.sigh_irregular.fraction_of_a_overlapped_by_b, 0.1);
end

function testCompactCombinesBeltsAndKeepsZeroDistinctFromUnavailable(testCase)
    assessable = true(900, 11);
    [burden, overlap, evidence] = compact_fixture(900, assessable);
    compact = build_compact_phenotype_features(burden, overlap, evidence);
    validate_compact_phenotype_features(compact);
    verifyEqual(testCase, compact.values(4), 21);
    verifyEqual(testCase, compact.values(5), 1.5);
    verifyEqual(testCase, compact.values(10), 0.3, 'AbsTol', eps);
    verifyEqual(testCase, compact.values(12), 1.4);
    verifyEqual(testCase, compact.values(15), 35);
    verifyEqual(testCase, compact.values([13 16]), [0 0]);
    verifyTrue(testCase, all(compact.available([13 16])));

    names = get_labels('short');
    thoracic = strcmp(names, 'thoracic');
    async = strcmp(names, 'async');
    available = true(1, 11);
    available(thoracic | async) = false;
    evidence.rapid.recording_median_rr_diaph = NaN;
    evidence.deep.recording_median_ratio_diaph = NaN;
    burden_unavailable = compute_recording_label_burden(false(900, 11), ...
        names, available, empty_events(), 1, repmat(available, 900, 1));
    overlap_unavailable = compute_label_overlap_summary(false(900, 11), ...
        names, available, 1, repmat(available, 900, 1), empty_events());
    compact_unavailable = build_compact_phenotype_features( ...
        burden_unavailable, overlap_unavailable, evidence);
    verifyTrue(testCase, all(isnan(compact_unavailable.values(11:16))));
    verifyFalse(testCase, any(compact_unavailable.available(11:16)));
    verifyEqual(testCase, compact_unavailable.values(4), 20);
    verifyEqual(testCase, compact_unavailable.values(5), 1.4);
end

function testReviewedMaxSighRequiresContinuousFifteenMinutes(testCase)
    names = get_labels('short');
    N = 1800;
    scope = true(N, 11);
    sigh = strcmp(names, 'sigh');
    scope(:, sigh) = false;
    scope(1:800, sigh) = true;
    scope(1001:1800, sigh) = true;
    burden = compute_recording_label_burden(false(N, 11), names, ...
        true(1, 11), empty_events(), 1, scope);
    verifyTrue(testCase, isnan(burden.max_sighs_in_any_15_min_window));
    verifyFalse(testCase, burden.max_sighs_in_any_15_min_window_available);
    verifyEqual(testCase, ...
        burden.max_sighs_in_any_15_min_window_missing_reason, ...
        'insufficient_continuous_assessable_15_min_interval');
end

function testRecordingScopeSummariesHonorLayerAssessability(testCase)
    [data, features, diagnostics, spo2_ref, config] = evidence_fixture();
    names = get_labels('short');
    available = true(1, 11);
    reasons = repmat({'available'}, 1, 11);
    mask = false(10, 11);
    events = empty_events();
    automatic_scope = true(10, 11);
    reviewed_scope = false(10, 11);
    reviewed_scope(1:5, :) = true;
    automatic_burden = compute_recording_label_burden( ...
        mask, names, available, events, 1, automatic_scope);
    reviewed_burden = compute_recording_label_burden( ...
        mask, names, available, events, 1, reviewed_scope);

    automatic = build_label_evidence_summary(names, available, reasons, ...
        data, features, spo2_ref, diagnostics, automatic_burden, config, ...
        mask, events, automatic_scope);
    reviewed = build_label_evidence_summary(names, available, reasons, ...
        data, features, spo2_ref, diagnostics, reviewed_burden, config, ...
        mask, events, reviewed_scope);

    verifyEqual(testCase, automatic.rapid.recording_median_rr_lungs, 20);
    verifyEqual(testCase, reviewed.rapid.recording_median_rr_lungs, 10);
    verifyEqual(testCase, automatic.deep.recording_median_ratio_lungs, 2);
    verifyEqual(testCase, reviewed.deep.recording_median_ratio_lungs, 1);
    verifyEqual(testCase, automatic.irregular.recording_median_cov_lungs, 0.3, ...
        'AbsTol', eps);
    verifyEqual(testCase, reviewed.irregular.recording_median_cov_lungs, 0.1, ...
        'AbsTol', eps);
    verifyEqual(testCase, ...
        automatic.thoracic.recording_median_thoracic_to_abdominal_ratio, 2);
    verifyEqual(testCase, ...
        reviewed.thoracic.recording_median_thoracic_to_abdominal_ratio, 1);
    verifyEqual(testCase, ...
        automatic.async.recording_median_absolute_phase_deg, 30);
    verifyEqual(testCase, ...
        reviewed.async.recording_median_absolute_phase_deg, 10);
end

function [burden, overlap, evidence] = compact_fixture(N, assessable)
    names = get_labels('short');
    burden = compute_recording_label_burden(false(N, 11), names, ...
        true(1, 11), empty_events(), 1, assessable);
    overlap = compute_label_overlap_summary(false(N, 11), names, ...
        true(1, 11), 1, assessable, empty_events());
    evidence = struct();
    evidence.rapid = struct('available', true, 'availability_reason', '', ...
        'recording_median_rr_lungs', 20, ...
        'recording_median_rr_diaph', 22);
    evidence.deep = struct('available', true, 'availability_reason', '', ...
        'recording_median_ratio_lungs', 1.4, ...
        'recording_median_ratio_diaph', 1.6);
    evidence.irregular = struct('available', true, 'availability_reason', '', ...
        'recording_median_cov_lungs', 0.2, ...
        'recording_median_cov_diaph', 0.4);
    evidence.thoracic = struct('available', true, 'availability_reason', '', ...
        'recording_median_thoracic_to_abdominal_ratio', 1.4);
    evidence.async = struct('available', true, 'availability_reason', '', ...
        'recording_median_absolute_phase_deg', 35);
    evidence.sigh = struct('available', true, 'availability_reason', '');
end

function output = event(type, start_index, end_index, fs)
    output = struct('type', type, 'start_idx', start_index, ...
        'end_idx', end_index, 'start_t', (start_index - 1) / fs, ...
        'end_t', end_index / fs, ...
        'duration', (end_index - start_index + 1) / fs);
end

function [data, features, diagnostics, spo2_ref, config] = evidence_fixture()
    config = make_test_config();
    config.fs = 1;
    config.grid_step_sec = 1;
    t = (0:9)';
    low = ones(5, 1);
    high = 3 * ones(5, 1);
    ratio = [low; high];
    rate = [10 * low; 10 * high];
    cov = [0.1 * low; 0.5 * low];
    belt = struct( ...
        'peak_t', t, 'amp_ratio_session', ratio, ...
        'reference_quality', 'good', 'session_amplitude_available', true, ...
        'rate_slow_window_bpm', rate, 'rate_rapid_window_bpm', rate, ...
        'irregularity', struct('cov', cov, 'robust_cov', cov));
    balance = struct('analysis_window_sec', 1, ...
        'dominance_ratio_threshold', 1.5, ...
        'thoracic_ratio_window_median', ratio, ...
        'abdominal_ratio_window_median', ones(10, 1), ...
        'thoracic_to_abdominal_ratio', ratio, ...
        'thoracic_dominance_log_ratio', log(ratio), ...
        'thoracic_relative_fraction', ratio ./ (ratio + 1));
    features = struct('lungs', belt, 'diaph', belt, 'time_sec', t, ...
        'shallow_band_ratio', [0.5 0.8], 'deep_ratio_threshold', 1.2, ...
        'rate_windows_sec', struct('slow', 1, 'rapid', 1), ...
        'thoracoabdominal_balance', balance);

    phase = struct('available', true, 'time_sec', t, ...
        'absolute_mean_phase_deg', [10 * low; 50 * low], ...
        'resultant_length', ones(10, 1), ...
        'selected_resp_frequency_hz', 0.2 * ones(10, 1), ...
        'expected_resp_frequency_hz', 0.2 * ones(10, 1), ...
        'selected_to_expected_frequency_ratio', ones(10, 1), ...
        'reliable_phase_mask', true(10, 1));
    diagnostics.async = struct('valid_analysis', true, ...
        'reference_available', true, 'reference_quality', struct(), ...
        'skip_code', 0, 'error_message', '', ...
        'primary_method', 'wavelet_phase_offset', 'primary_available', true, ...
        'primary_availability_reason', 'available', 'comparison', struct(), ...
        'references', struct(), 'thresholds', struct(), ...
        'phase_coherence_high', ones(10, 1), ...
        'phase_coherence_mid', ones(10, 1), ...
        'phase_coherence_low', ones(10, 1), ...
        'deviation_bin_count', zeros(10, 1), ...
        'methods', struct('wavelet_phase_offset', phase));
    raw = struct('excursion_ratio', ones(10, 1), ...
        'evaluable_endpoint_mask', true(10, 1));
    diagnostics.apnea = struct('amplitude_path_available', true, ...
        'raw_excursion_path_available', true, ...
        'amplitude_support_belts', 'both', ...
        'raw_excursion_support_belts', 'both', ...
        'amplitude_state_mask', false(10, 1), ...
        'raw_fallback_state_mask', false(10, 1), ...
        'combined_endpoint_mask', false(10, 1), ...
        'raw_excursion', struct('lungs', raw, 'diaph', raw));
    sigh_belt = struct('decision_threshold', 2, ...
        'sigh_ratio', ones(10, 1), 'evaluable_mask', true(10, 1), ...
        'available', true);
    diagnostics.sigh = struct('lungs', sigh_belt, 'diaph', sigh_belt);
    method = struct('available', true, 'event_count', 0, ...
        'event_duration_sec', 0, ...
        'lungs', struct('available', true, 'index', zeros(10, 1), ...
            'h', zeros(10, 1), 'fm_hz', zeros(10, 1)), ...
        'diaph', struct('available', true, 'index', zeros(10, 1), ...
            'h', zeros(10, 1), 'fm_hz', zeros(10, 1)));
    diagnostics.periodic = struct('primary_method', 'eami', ...
        'eami', method, 'guyot', method);
    diagnostics.desat = struct();
    data = zeros(10, 6);
    spo2_ref = struct('median_percent', NaN);
end
