function tests = test_asynchrony_phase_offset
% Focused tests for complementary respiratory wavelet phase offset.

    tests = functiontests(localfunctions);
end

function testKnownStablePhaseOffsets(testCase)
    angles = [0 30 90 180];
    tolerance_deg = 2;
    for angle_deg = angles
        [data, config] = phase_fixture(angle_deg, 1);
        metrics = compute_respiratory_phase_offset_metrics(data, [], config);
        observed = median(metrics.absolute_mean_phase_deg, 'omitnan');

        verifyTrue(testCase, metrics.available, metrics.availability_reason);
        verifyEqual(testCase, observed, angle_deg, ...
            'AbsTol', tolerance_deg);
        verifyGreaterThan(testCase, ...
            median(metrics.resultant_length, 'omitnan'), 0.98);
        verifyEqual(testCase, ...
            median(metrics.selected_resp_frequency_hz, 'omitnan'), ...
            0.25, 'AbsTol', 0.02);
    end
end

function testCircularMeanWrapsAtOneHundredEightyDegrees(testCase)
    [mean_phase, resultant] = circular_phase_summary( ...
        deg2rad([179 -179]));

    verifyEqual(testCase, abs(rad2deg(mean_phase)), 180, 'AbsTol', 0.01);
    verifyGreaterThan(testCase, resultant, 0.99);
end

function testStableOppositionIsDetectedWithoutAutomaticInversion(testCase)
    [data, config] = phase_fixture(180, 1);
    missing_reference = struct('available', false);
    [events, diagnostics] = detect_respiratory_asynchrony( ...
        data, missing_reference, [], config);
    phase = diagnostics.methods.wavelet_phase_offset;

    verifyNotEmpty(testCase, events);
    verifyEqual(testCase, diagnostics.primary_method, ...
        'wavelet_phase_offset');
    verifyTrue(testCase, diagnostics.primary_available);
    verifyEqual(testCase, median(phase.absolute_mean_phase_deg, 'omitnan'), ...
        180, 'AbsTol', 2);
    verifyGreaterThan(testCase, median(phase.resultant_length, 'omitnan'), 0.98);
    verifyEqual(testCase, phase.polarity_convention, ...
        'recorded_channel_polarity_thoracic_minus_abdominal_no_inversion');
    verifyEqual(testCase, phase.reference_normalization, 'none');
    verifyEqual(testCase, phase.provenance.polarity_convention, ...
        phase.polarity_convention);
end

function testAmplitudeScalingDoesNotChangePhase(testCase)
    [data, config] = phase_fixture(90, 1);
    scaled = data;
    scaled(:, 1) = 7 * scaled(:, 1);
    scaled(:, 2) = 0.2 * scaled(:, 2);
    original = compute_respiratory_phase_offset_metrics(data, [], config);
    transformed = compute_respiratory_phase_offset_metrics(scaled, [], config);

    verifyEqual(testCase, ...
        median(transformed.absolute_mean_phase_deg, 'omitnan'), ...
        median(original.absolute_mean_phase_deg, 'omitnan'), ...
        'AbsTol', 0.1);
    verifyEqual(testCase, ...
        median(transformed.resultant_length, 'omitnan'), ...
        median(original.resultant_length, 'omitnan'), ...
        'AbsTol', 0.01);
end

function testFlatSegmentsAreUnevaluable(testCase)
    [data, config, time_sec] = phase_fixture(90, 1);
    flat = time_sec >= 45 & time_sec < 75;
    data(flat, :) = 0;
    metrics = compute_respiratory_phase_offset_metrics(data, [], config);
    central = metrics.time_sec >= 55 & metrics.time_sec < 65;

    verifyFalse(testCase, any(metrics.valid_phase_mask(central)));
    verifyFalse(testCase, any(metrics.reliable_phase_mask(central)));
    verifyTrue(testCase, all(isnan( ...
        metrics.absolute_mean_phase_deg(central))));
end

function testMissingBeltMakesPhaseMethodUnavailable(testCase)
    [data, config] = phase_fixture(90, 1);
    config.channels.diaph_idx = [];
    metrics = compute_respiratory_phase_offset_metrics(data(:, 1), [], config);

    verifyFalse(testCase, metrics.available);
    verifyEqual(testCase, metrics.availability_reason, ...
        'missing_respiratory_belt_channel');
end

function testMissingReferenceDoesNotBlockPhasePrimary(testCase)
    [data, config] = phase_fixture(90, 1);
    reference = struct('available', false);
    [events, diagnostics] = detect_respiratory_asynchrony( ...
        data, reference, [], config);

    verifyTrue(testCase, diagnostics.primary_available);
    verifyNotEmpty(testCase, events);
    verifyFalse(testCase, diagnostics.methods.wavelet_coherence_drop.available);
    verifyTrue(testCase, diagnostics.methods.wavelet_phase_offset.available);
    verifyFalse(testCase, diagnostics.comparison.available);
    verifyEqual(testCase, diagnostics.comparison.jointly_assessable_sec, 0);
    verifyTrue(testCase, isnan(diagnostics.comparison.agreement_fraction));
end

function testSelectedPhaseAvailabilityAndAssessabilityPropagate(testCase)
    [data, config] = phase_fixture(90, 1);
    [~, diagnostics] = detect_respiratory_asynchrony( ...
        data, struct('available', false), [], config);
    resp_features = minimal_resp_features();
    [available, reason] = compute_label_availability( ...
        {'async'}, resp_features, struct(), diagnostics, ...
        struct(), struct(), struct());
    [assessable, info] = compute_label_assessable_mask( ...
        data, {'async'}, available, diagnostics, ...
        diagnostics.methods.wavelet_phase_offset.time_sec, config);

    verifyTrue(testCase, available);
    verifyEqual(testCase, reason, {'available'});
    verifyTrue(testCase, any(assessable));
    verifyFalse(testCase, all(assessable));
    verifyEqual(testCase, info.version, 'label_assessability_v2');
end

function testUnavailableSelectedMethodDoesNotFallBack(testCase)
    [data, config] = phase_fixture(20, 1);
    config.async.phase_offset.min_magnitude_fraction = 1e6;
    reference = struct( ...
        'available', true, ...
        'complete', true, ...
        'reference_start_t', 0, ...
        'reference_end_t', 120);

    [events, diagnostics] = detect_respiratory_asynchrony( ...
        data, reference, [], config);

    verifyTrue(testCase, ...
        diagnostics.methods.wavelet_coherence_drop.available);
    verifyFalse(testCase, ...
        diagnostics.methods.wavelet_phase_offset.available);
    verifyFalse(testCase, diagnostics.primary_available);
    verifyEmpty(testCase, events);
end

function testLegacyCoherencePayloadAndEventsRemainUnchanged(testCase)
    [data, config] = phase_fixture(20, 1);
    config.async = rmfield(config.async, ...
        {'primary_method', 'compare_methods'});
    reference = struct( ...
        'available', true, ...
        'complete', true, ...
        'reference_start_t', 0, ...
        'reference_end_t', 120);
    legacy = compute_respiratory_asynchrony_metrics( ...
        data, [], reference, config);
    [expected_events, ~] = sustained_condition_to_events( ...
        legacy.low_coherence_mask, legacy.time_sec, config.fs, ...
        size(data, 1), legacy.min_dur_sec, 'respiratory_asynchrony');
    [actual_events, diagnostics] = detect_respiratory_asynchrony( ...
        data, reference, [], config);

    verifyEqual(testCase, actual_events, expected_events);
    verifyEqual(testCase, diagnostics.valid_analysis, legacy.valid_analysis);
    verifyEqual(testCase, diagnostics.phase_coherence_high, ...
        legacy.phase_coherence_high);
    verifyEqual(testCase, diagnostics.phase_coherence_mid, ...
        legacy.phase_coherence_mid);
    verifyEqual(testCase, diagnostics.phase_coherence_low, ...
        legacy.phase_coherence_low);
    verifyEqual(testCase, diagnostics.low_coherence_mask, ...
        legacy.low_coherence_mask);
    verifyEqual(testCase, diagnostics.thresholds, legacy.thresholds);
    verifyEqual(testCase, diagnostics.primary_method, ...
        'wavelet_coherence_drop');
end

function [data, config, time_sec] = phase_fixture(angle_deg, amplitude)
    fs = 20;
    time_sec = (0:1/fs:(120 - 1/fs))';
    data = [ ...
        amplitude * sin(2 * pi * 0.25 * time_sec), ...
        amplitude * sin(2 * pi * 0.25 * time_sec + deg2rad(angle_deg))];
    config = struct();
    config.fs = fs;
    config.grid_step_sec = 1;
    config.subject = 999;
    config.measure = 1;
    config.make_figs_visible = 'off';
    config.data_columns = {'Resp-Lungs', 'Resp-Diaphragm'};
    config.channels = struct( ...
        'lungs_idx', 1, 'diaph_idx', 2, 'spo2_idx', []);
    config.problems = struct('missing_lung_belt', zeros(0, 2));
    config.async = struct( ...
        'primary_method', 'wavelet_phase_offset', ...
        'compare_methods', true, ...
        'analysis_fs', 20, ...
        'f0', 1, ...
        'fmin', 0.052, ...
        'low_mid_cut_hz', 0.145, ...
        'mid_high_cut_hz', 0.6, ...
        'fmax', 2, ...
        'tlphcoh_cycles', 10, ...
        'min_dur_sec', 5, ...
        'reference_mad_k', 3, ...
        'min_abs_drop', 0.15, ...
        'min_deviating_bins', 1, ...
        'plot_step_sec', 5, ...
        'do_plot', false, ...
        'phase_offset', struct( ...
            'angle_threshold_deg', 30, ...
            'summary_cycles', 5, ...
            'min_resultant_length', 0.80, ...
            'min_valid_fraction', 0.80, ...
            'min_magnitude_fraction', 0.05, ...
            'frequency_min_hz', 0.145, ...
            'frequency_max_hz', 0.6));
end

function features = minimal_resp_features()
    belt = struct( ...
        'available', true, ...
        'session_amplitude_available', false, ...
        'rate_slow_window_bpm', [], ...
        'rate_rapid_window_bpm', [], ...
        'irregularity', struct('cov', []));
    features = struct( ...
        'lungs', belt, ...
        'diaph', belt, ...
        'thoracoabdominal_balance', struct('available', false));
end
