function b = reset_respiration_trough_override( ...
    b, left_peak_idx, right_peak_idx, config)
% RESET_RESPIRATION_TROUGH_OVERRIDE Restore one pair's automatic trough.
% The peak sample indices must identify a currently consecutive pair. Other
% pair-anchored manual trough overrides are retained.

    if ~isstruct(b) || ~isfield(b, 'x0') || ~isfield(b, 'peak_idx') || ...
            numel(b.peak_idx) < 2
        error('MAGMA:Respiration:InvalidTroughEditState', ...
            'Trough reset requires a signal and at least two breath peaks.');
    end
    if ~isnumeric(left_peak_idx) || ~isscalar(left_peak_idx) || ...
            ~isfinite(left_peak_idx) || left_peak_idx ~= round(left_peak_idx) || ...
            ~isnumeric(right_peak_idx) || ~isscalar(right_peak_idx) || ...
            ~isfinite(right_peak_idx) || right_peak_idx ~= round(right_peak_idx)
        error('MAGMA:Respiration:InvalidTroughSample', ...
            'Surrounding peak indices must be finite integers.');
    end
    pair_exists = any(b.peak_idx(1:end-1) == left_peak_idx & ...
        b.peak_idx(2:end) == right_peak_idx);
    if ~pair_exists
        error('MAGMA:Respiration:TroughPeakPairChanged', ...
            'The selected surrounding peaks are no longer consecutive.');
    end

    overrides = zeros(0, 3);
    if isfield(b, 'trough_overrides') && ...
            isnumeric(b.trough_overrides) && ...
            size(b.trough_overrides, 2) == 3
        overrides = double(b.trough_overrides);
        valid = all(isfinite(overrides), 2) & ...
            all(overrides == round(overrides), 2) & all(overrides >= 1, 2);
        overrides = overrides(valid, :);
    end
    same_pair = overrides(:, 1) == left_peak_idx & ...
        overrides(:, 2) == right_peak_idx;
    b.trough_overrides = overrides(~same_pair, :);
    b = recompute_respiration_breath_fields( ...
        b, b.x0, b.peak_idx, config);
end
